// Package codex adapts the OpenAI Codex CLI — the first Phase 1 harness
// (spec §5.1, §19), chosen so ChatGPT subscription auth is exercised
// from day one.
//
// Invocation flags are pinned per harness version here and verified
// against vendor docs at upgrade time. The adapter runs `codex exec`
// (headless mode) with --json and parses the JSONL event stream.
package codex

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/kidus-tiliksew/conveyor/internal/adapter"
)

// PinnedVersion is the Codex CLI version these flags were validated
// against (live end-to-end runs on 2026-07-10: exec --json event
// schema, --sandbox danger-full-access, subscription auth). Bump
// deliberately; adapters break on silent CLI drift.
const PinnedVersion = "0.142.0"

type Adapter struct {
	// Binary is the codex executable; overridable for tests.
	Binary string
	// Home is mapped to CODEX_HOME inside the sandbox so session state
	// lands in the job directory and becomes an artifact by construction
	// (spec §8.3 note 2).
	Home string
	// ContainerConfined disables codex's native sandbox
	// (--sandbox danger-full-access): under Tier A the container is the
	// confinement boundary, and bwrap/Landlock cannot create namespaces
	// inside an unprivileged container anyway. Never set outside a
	// container — Tier B relies on the native sandbox (spec §8.5).
	ContainerConfined bool
}

func New() *Adapter {
	return &Adapter{Binary: "codex"}
}

func (a *Adapter) Name() string { return "codex" }

func (a *Adapter) Capabilities() adapter.Capabilities {
	return adapter.Capabilities{
		MultiRepo:  true,
		Resume:     true, // codex exec resume; fidelity measured by the Phase 1 experiment (spec §20.2)
		JSONStream: true,
		AuthModes:  []string{"personal_sub", "team_sub", "api"},
		// Seatbelt (macOS) / Landlock+seccomp (Linux) — candidate for
		// Tier B confinement (spec §8.5).
		NativeSandbox: true,
	}
}

func (a *Adapter) Run(ctx context.Context, spec adapter.RunSpec) (<-chan adapter.Event, error) {
	if err := a.checkVersion(ctx); err != nil {
		return nil, err
	}
	if err := a.preparePolicy(spec.Policy); err != nil {
		return nil, err
	}
	// The adapter owns unattended permission posture (spec §8.5): never
	// inherit an interactive approval workflow. Command prefixes are loaded
	// from the job-scoped CODEX_HOME/rules generated above. Codex rules are a
	// second layer; Tier A's container remains the confinement boundary.
	// Session identity is captured authoritatively from the pinned CLI's
	// structured thread.started event (spec §8.3 note 1).
	args := []string{
		"exec", "--json", "--cd", spec.Workdir,
		"-c", `approval_policy="never"`,
		// Codex excludes names containing KEY/SECRET/TOKEN from tool shells
		// by default. Conveyor already scopes exactly which environment
		// values enter the container, so retain those deliberate injections.
		"-c", "shell_environment_policy.ignore_default_excludes=true",
	}
	if a.ContainerConfined {
		args = append(args, "--sandbox", "danger-full-access")
	} else {
		args = append(args, "--sandbox", "workspace-write")
	}
	args = append(args, spec.Prompt)
	return a.stream(ctx, spec.Workdir, args)
}

func (a *Adapter) Resume(ctx context.Context, sessionRef string, feedback string) (<-chan adapter.Event, error) {
	if err := a.checkVersion(ctx); err != nil {
		return nil, err
	}
	// `exec resume` (validated against PinnedVersion) has no --sandbox
	// flag; the config override is its equivalent. The session carries
	// its own working directory, so the repo check on the caller's cwd
	// is skipped.
	args := []string{
		"exec", "resume", sessionRef, "--json", "--skip-git-repo-check",
		"-c", `approval_policy="never"`,
		"-c", "shell_environment_policy.ignore_default_excludes=true",
	}
	if a.ContainerConfined {
		args = append(args, "-c", `sandbox_mode="danger-full-access"`)
	}
	args = append(args, feedback)
	return a.stream(ctx, "", args)
}

func (a *Adapter) preparePolicy(policy adapter.ToolPolicy) error {
	if a.Home == "" {
		if len(policy.AllowedCommands) == 0 && len(policy.DeniedCommands) == 0 {
			return nil
		}
		return fmt.Errorf("Codex policy requires a job-scoped CODEX_HOME")
	}
	rulesDir := filepath.Join(a.Home, "rules")
	rulesPath := filepath.Join(rulesDir, "conveyor.rules")
	if len(policy.AllowedCommands) == 0 && len(policy.DeniedCommands) == 0 {
		if err := os.Remove(rulesPath); err != nil && !os.IsNotExist(err) {
			return err
		}
		return nil
	}
	if err := os.MkdirAll(rulesDir, 0o700); err != nil {
		return err
	}
	var rules strings.Builder
	rules.WriteString("# Generated by Conveyor for this job (spec §8.5).\n")
	writeRule := func(pattern []string, decision, justification string) error {
		if len(pattern) == 0 {
			return fmt.Errorf("empty %s command pattern", decision)
		}
		rules.WriteString("prefix_rule(pattern = [")
		for i, token := range pattern {
			if token == "" || strings.ContainsRune(token, '\x00') {
				return fmt.Errorf("invalid %s command pattern", decision)
			}
			if i > 0 {
				rules.WriteString(", ")
			}
			rules.WriteString(strconv.Quote(token))
		}
		fmt.Fprintf(&rules, "], decision = %s, justification = %s)\n", strconv.Quote(decision), strconv.Quote(justification))
		return nil
	}
	for _, pattern := range policy.AllowedCommands {
		if err := writeRule(pattern, "allow", "Allowed by Conveyor's per-job tool policy"); err != nil {
			return err
		}
	}
	for _, pattern := range policy.DeniedCommands {
		if err := writeRule(pattern, "forbidden", "Blocked by Conveyor's per-job tool policy"); err != nil {
			return err
		}
	}
	tmp, err := os.CreateTemp(rulesDir, ".conveyor-rules-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if err := tmp.Chmod(0o600); err != nil {
		_ = tmp.Close()
		return err
	}
	if _, err := tmp.WriteString(rules.String()); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpPath, rulesPath)
}

func (a *Adapter) checkVersion(ctx context.Context) error {
	return adapter.CheckVersion(ctx, adapter.VersionSpec{
		Binary: a.Binary, Name: "codex", Want: "codex-cli " + PinnedVersion,
	})
}

func (a *Adapter) stream(ctx context.Context, dir string, args []string) (<-chan adapter.Event, error) {
	var env []string
	if a.Home != "" {
		env = append(env, "CODEX_HOME="+a.Home)
	}
	return adapter.StreamCommand(ctx, adapter.StreamSpec{
		Binary: a.Binary, Args: args, Dir: dir, Env: env, Name: "codex",
		MaxLineBytes: 16 * 1024 * 1024, Parse: parseLine,
	})
}

// parseLine maps one Codex JSONL thread event onto the normalized event
// set. Current `codex exec --json` emits thread.started, turn.started,
// item.started/updated/completed (item detail nested under "item"), and
// turn.completed (token usage nested under "usage"). Anything
// unrecognized passes through with its raw payload so no information is
// dropped before the transcript store.
func parseLine(line []byte) adapter.Event {
	var probe struct {
		Type     string `json:"type"`
		ThreadID string `json:"thread_id"` // thread.started
		Item     struct {
			Type     string `json:"type"`
			ItemType string `json:"item_type"` // older builds nest the type here
			Text     string `json:"text"`
		} `json:"item"`
		Usage struct {
			InputTokens  int64 `json:"input_tokens"`
			OutputTokens int64 `json:"output_tokens"`
		} `json:"usage"`
		Error struct {
			Message string `json:"message"`
		} `json:"error"`
	}
	ev := adapter.Event{At: time.Now(), Payload: json.RawMessage(append([]byte(nil), line...))}
	if err := json.Unmarshal(line, &probe); err != nil {
		ev.Kind = adapter.EventAssistantText
		ev.Text = string(line)
		return ev
	}

	itemType := probe.Item.Type
	if itemType == "" {
		itemType = probe.Item.ItemType
	}

	switch probe.Type {
	case "item.started", "item.updated", "item.completed":
		switch itemType {
		case "agent_message", "reasoning":
			ev.Kind = adapter.EventAssistantText
			ev.Text = probe.Item.Text
		case "error":
			ev.Kind = adapter.EventError
			ev.Err = probe.Item.Text
		default:
			// command_execution, file_change, mcp_tool_call, web_search, …
			ev.Tool = itemType
			if probe.Type == "item.started" {
				ev.Kind = adapter.EventToolCall
			} else {
				ev.Kind = adapter.EventToolResult
			}
		}
	case "turn.completed":
		ev.Kind = adapter.EventTokenUsage
		ev.Usage = &adapter.TokenUsage{In: probe.Usage.InputTokens, Out: probe.Usage.OutputTokens}
	case "turn.failed", "error":
		ev.Kind = adapter.EventError
		ev.Err = probe.Error.Message
	case "thread.started":
		// The thread ID is the session ref for `codex exec resume`,
		// captured here as the harness announces it (spec §8.3 note 1).
		ev.Kind = adapter.EventSessionStart
		ev.SessionRef = probe.ThreadID
	default:
		// turn.started, unknown: raw payload only.
		ev.Kind = adapter.EventAssistantText
	}
	return ev
}
