package storetest

import "strings"

// suiteMethods declares the public methods each suite exercises, including
// its shared fixtures and taskops command adapters. Additions to Backend
// require an explicit declaration and a behavioral case (DEC-38).
var suiteMethods = map[string][]string{
	"EmptyProjections":           strings.Fields(`GetLatestJob GetReferenceDocument GetReferenceDocumentVersion GetSpecVersion GetSystemDesignVersion GetTaskByIntakeKey GetTranscript ListActiveSystemDesignDriftCounts ListActivityMarkers ListActivityMarkersForTasks ListCallerAttentionTaskPage ListCheckpointContextCandidates ListDependentTaskIDs ListFeatures ListGovernanceDesigns ListJobs ListLineageContextRecords ListLineageNodeRecords ListPlanningBundles ListRequirementDeliveryEventsForTasks ListRequirementDeliveryLineageByRequirement ListRequirementEventsByRequirement ListRequirementVersionsByRequirement ListSystemDesignEventsByDocument ListSystemDesignVersionsByDocument ListTaskPage ListWorkOrders ListWorkOrdersForTasks RequirementExists`),
	"ProjectionReads":            strings.Fields(`AssignTaskFeature CountEventsSinceHumanIntervention CreateFeature CreateStageWorkOrderCommand CreateTask GetLatestJob GetTranscript ListEvents ListEventsAfter ListFeatures ListJobs ListLineageContextRecords ListLineageNodeRecords UpdateJob UpsertTranscript ValidateTaskDependencies WithTaskSideEffectLock`),
	"WorkspaceControl":           strings.Fields(`BootstrapWorkspaceConfig GetWorkspace ListWorkspaces Log ReconcileBlueprintClosures ReconcileGitHubLifecycles ReconcileQueuedTasks RuntimeConfig UpdateWorkspaceConfig WorkspaceConfig`),
	"CommandRefusals":            strings.Fields(`ApplyTaskCommand CancelPlanRevisionWorkOrderCommand ChangeTaskSetupCommand ClaimWorkOrderCommand CreateClaimedVerificationEvidence CreateConflictFixCommand CreateIntervention CreateStageWorkOrderCommand CreateTask GetArtifact GetTask GetWorkOrder ListEvents RefreshWorkOrderHarnessSnapshot RemoveTaskDependency RequestChangesCommand`),
	"ApprovalRefresh":            strings.Fields(`AdvanceTaskRefreshHead BindTaskApproval CreateTask GetTask MarkTaskApprovalStale SkipTaskRefresh`),
	"PlanningReads":              strings.Fields(`ApprovePlanningBundle CreateArtifact CreatePlanningBundle CreatePlanningSession CreateReferenceDocument GetArtifactForPlanningSession GetReferenceDocument GetReferenceDocumentVersion ListReferenceDocumentVersions ListTasks RejectPlanningBundle`),
	"Blueprint":                  strings.Fields(`ApplyTaskCommand ApproveSpecVersion ApproveSpecVersionAndMaterialize CountEvents CreateFeature CreateSpecVersion CreateTask GetApprovedSpecVersion GetLatestSpecVersion GetTask ListBlockingTaskIDs ListEvents ListTasks`),
	"Requirements":               strings.Fields(`AbandonPlanningSession AcknowledgeRequirementStaleness AppendEvent AppendPlanningMessage ApplyTaskCommand ArchiveRequirement ArchiveSystemDesign ClaimWorkOrderCommand ConfirmRequirementServes ConfirmRequirementVersion ConfirmSystemDesignVersion ConfirmTaskContextProposal CreateArtifact CreateJob CreatePlanningSession CreateRequirement CreateSystemDesign CreateTask CreateWorkspace DismissRequirementServes DismissTaskContextProposal FinalizePlanningSession GetArtifact GetPlanningSession GetRequirement GetRequirementVersion GetSystemDesign GetTask LineageNodeExists ListArtifacts ListDocumentEventPage ListEvents ListLineageLinks ListPendingProposals ListPlanningMessages ListPlanningSessions ListRequirementEvents ListRequirementServes ListRequirementVersions ListRequirements ListSystemDesignEvents ListSystemDesigns ListTaskContextProposals ListTasks PendingProposalsProjection PinPlanningSessionRepo ProposeRequirementServes ProposeRequirementVersion ProposeSystemDesignVersion ProposeTaskContext RebuildLineage RecordDrift RecordPlanningExplorationTokens RecordSystemDesignConsulted ResolveDrift RestoreRequirement RestoreSystemDesign UpdateTaskContext WithPlanningSessionFinalization WithPlanningSessionRun`),
	"VersionDismissal":           strings.Fields(`ConfirmRequirementVersion ConfirmSystemDesignVersion CreateRequirement CreateSystemDesign DismissRequirementVersion DismissSystemDesignVersion ListRequirementEvents ListSystemDesignEvents ProposeRequirementVersion ProposeSystemDesignVersion`),
	"Lineage":                    strings.Fields(`AcceptReviewDecisionCommand AppendEvent ConfirmDecision ConfirmRequirementVersion ConfirmSystemDesignVersion CreateArtifact CreateJob CreatePlanningSession CreateReferenceDocument CreateRequirement CreateSpecVersion CreateSystemDesign CreateTask CreateTaskWithDependencies CreateTaskWithDependenciesAndContext DismissDecision FinalizePlanningSession GetDecision ListArtifactsForLineage ListEvents ListLineageLinks ListLineageNeighborhood ListRequirementDeliveryLineage ListSystemDesignEvents ListSystemDesignVersions ProposeDecision ProposeRequirementVersion ProposeSystemDesignVersion RebuildLineage RecordReferenceDocumentConsulted SupersedeReferenceDocument UpdateTaskContext`),
	"CheckpointDecisionRequests": strings.Fields(`ClaimWorkOrderCommand CreateJob CreateTask CreateWorkOrderCommand GetWorkOrder ListEvents ReleaseWorkerClaimCommand`),
	"CheckpointRenewal":          strings.Fields(`ClaimWorkOrderCommand CreateJob CreateTask CreateWorkOrderCommand GetWorkOrder ReleaseWorkerClaimCommand RenewWorkerClaimCommand`),
	"ForgeAuthorIdentity":        strings.Fields(`AppendEvent CreateJob CreateTask GetGitHubLifecycle GetReviewPublication ListEvents QueueGitHubLifecycle QueueReviewPublication ReconcileReviewPublications UpdateGitHubLifecycle UpdateReviewPublication`),
	"PlanRevision":               strings.Fields(`ApproveSpecVersion ClaimWorkOrderCommand CreateJob CreateSpecVersion CreateTask GetTask GetWorkOrder ListEvents ReleaseWorkerClaimCommand RequestPlanRevisionCommand`),
	"ReferenceDocuments":         strings.Fields(`AppendEvent CreatePlanningSession CreateReferenceDocument CreateTask DeleteReferenceDocument ListReferenceDocumentEvents ListReferenceDocuments RecordReferenceDocumentConsulted SupersedeReferenceDocument`),
	"SystemDesignProposals":      strings.Fields(`ConfirmSystemDesignVersion CreateSystemDesign ListPendingSystemDesignVersionsForTask ListSystemDesignEvents ListSystemDesignProposalEventsForTask ListSystemDesignProposalVersionsForTask ProposeSystemDesignVersion`),
	"PlanningBundles":            strings.Fields(`ApprovePlanningBundle ConfirmRequirementVersion ConfirmSystemDesignVersion CreatePlanningBundle CreatePlanningSession CreateRequirement CreateSystemDesign EnsureTaskEnqueued FinalizePlanningSession GetPlanningBundle GetRequirementVersion ListEvents ListLineageLinks RebuildLineage UpdateTaskContext`),
	"SystemDesignDrift":          strings.Fields(`AppendEvent AttachSubmissionGovernance ConfirmSystemDesignVersion CreateSystemDesign CreateTask LinkTask ListEvents ListSystemDesignEvents MonitorStatus Observe ProposeSystemDesignVersion RecordDrift ResolveCausalSystemDesignMerge`),
	"TaskContextRepin":           strings.Fields(`AppendEvent ClaimWorkOrderCommand ConfirmSystemDesignVersion CreateJob CreateSystemDesign CreateTaskWithDependenciesAndContext ListEvents ProposeSystemDesignVersion`),
	"DependencyAddition":         strings.Fields(`AddTaskDependency ClaimWorkOrderCommand CountEvents CreateJob CreateTask GetWorkOrder ListDependencyBlockers ListEvents`),
	"TaskOperationsPagination":   strings.Fields(`CreateTask ListTaskOperations ListTasks ListTasksFiltered`),
	"TaskLifecycle":              strings.Fields(`CancelTaskCommand CreateTask GetTask ListEvents ListInterventions SetTaskHold UpdateTaskClassification`),
	"TaskEventAtomicity":         strings.Fields(`CreateTask GetTask ListEvents SetTaskHold`),
	"Workers":                    strings.Fields(`AuthenticateWorker ConsumeWorkerPairing CreateWorker CreateWorkerPairing HeartbeatWorker ListEvents ListHarnessModelFailures ListWorkers RevokeWorker`),
	"WorkOrders":                 strings.Fields(`CancelTaskCommand ClaimWorkOrderCommand CreateStageWorkOrderCommand CreateTask FinalizeWorkOrderAttemptObservability GetWorkOrder GetWorkOrderActivitySnapshot ListTaskWorkOrdersSnapshot ListWorkOrderTranscriptCaptures PreemptWorkOrderCommand RecordWorkOrderAttemptCheckpoint RecordWorkOrderContinuation RecoverWorkOrderCommand ReleaseWorkerClaimCommand RenewWorkerClaimCommand UpsertWorkOrderActivitySnapshot`),
	"WorkOrderClocks":            strings.Fields(`ApplyWorkOrderClock ClaimWorkOrderCommand CreateStageWorkOrderCommand CreateTask GetWorkOrder ListElapsedWorkOrderTaskIDs RecoverWorkOrderCommand RedispatchWorkOrderCommand UpdateWorkOrderCommand`),
	"ReviewRounds":               strings.Fields(`ClaimWorkOrderCommand CreateReviewRoundCommand CreateTask GetWorkOrder ListElapsedWorkOrderTaskIDs ListTaskWorkOrders RecoverInterruptedReviewRoundCommand RetryReviewRoundCommand UpdateWorkOrderCommand`),
	"ReviewAcceptance":           strings.Fields(`AcceptReviewDecisionCommand CreateReviewRoundCommand CreateTask GetTask ListEvents`),
	"Decisions":                  strings.Fields(`ConfirmDecision ConfirmRequirementVersion CreateRequirement DismissDecision DismissDecisionSupersessionSweep GetDecision ListDecisions ProposeDecision ProposeRequirementVersion`),
	"ArchiveRestore":             strings.Fields(`ArchiveRequirement ArchiveSystemDesign ConfirmRequirementVersion ConfirmSystemDesignVersion CreateRequirement CreateSystemDesign GetRequirement GetSystemDesign ListRequirementVersions ListSystemDesignVersions RestoreRequirement RestoreSystemDesign`),
	"Monitor":                    strings.Fields(`AuditMonitor AuditTask CreateTask FindOpenMonitorTask LinkTask MonitorStatus Observe RecordDrift RecordMonitorFailure RecordMonitorSuccess ResolveDrift WithMonitorSignalClassLock`),
	"TaskFilter":                 strings.Fields(`AppendEvent BootstrapIdentity CreateTask GrantWorkspaceRole ListTaskOperations ListTasksFiltered ProvisionIdentityUser SetTaskAssigneeCommand VerifyPersonalAccessToken`),
	"TaskAssigneeMembership":     strings.Fields(`BootstrapIdentity CreateTask GetTask GrantWorkspaceRole ProvisionIdentityUser RevokeWorkspaceRole SetTaskAssigneeCommand VerifyPersonalAccessToken`),
	"Identity":                   strings.Fields(`BootstrapIdentity GetCallerIdentity ProvisionIdentityUser VerifyCredential VerifyPersonalAccessToken`),
	"Membership":                 strings.Fields(`AuthorizeDeployment AuthorizeWorkspace BootstrapIdentity GrantWorkspaceRole ListWorkspaceInvitations ListWorkspaceMembers ListWorkspacesForUser ProvisionIdentityUser RecordInvitationDelivery RevokeWorkspaceInvitation RevokeWorkspaceRole VerifyPersonalAccessToken`),
	"InvitationSessions":         strings.Fields(`BootstrapIdentity GrantWorkspaceRole IssueSignInLink RedeemSignInLink RevokeDashboardSession SetOwnDisplayName SetOwnPassword SignInWithPassword VerifyDashboardSession VerifyPersonalAccessToken`),
	"Tokens":                     strings.Fields(`BootstrapIdentity ConfigureForgeTokenEncryptionKey DeleteForgeToken DeleteWorkspaceForgeToken GetForgeTokenForUse GetForgeTokenStatus GetWorkspaceForgeTokenForUse GetWorkspaceForgeTokenStatus IssueAgentCredential IssueOwnPersonalAccessToken ListForgeTokensForRedaction ListOwnPersonalAccessTokens RevokeOwnPersonalAccessToken RevokeRunAgentCredential StoreForgeToken StoreWorkspaceForgeToken VerifyCredential VerifyPersonalAccessToken`),
}
