package postgres

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/kidus-tiliksew/conveyor/internal/core"
	"github.com/kidus-tiliksew/conveyor/internal/gitx"
	"github.com/kidus-tiliksew/conveyor/internal/store"
	"github.com/kidus-tiliksew/conveyor/internal/store/postgres/db"
)

const planningBundleSelect = `SELECT id,session_id,title,documents,tasks,status,COALESCE(created_by,''),COALESCE(decided_by,''),created_at,decided_at,workspace_id FROM planning_bundles`

func (s *Store) CreatePlanningBundle(ctx context.Context, bundle core.PlanningBundle) (core.PlanningBundle, error) {
	bundle.Workspace = workspace(ctx)
	// Resolve the deterministic identity before the locked lookup. Full shape
	// validation follows identity adoption because a retry may omit the task IDs
	// generated by its first successful finalize.
	bundle.ID = strings.TrimSpace(bundle.ID)
	actor := store.ActorFromContext(ctx)
	var result core.PlanningBundle
	err := s.inTx(ctx, func(tx pgx.Tx, q *db.Queries) error {
		existing, existingErr := scanPlanningBundle(tx.QueryRow(ctx, planningBundleSelect+` WHERE workspace_id=$1 AND id=$2 FOR UPDATE`, bundle.Workspace, bundle.ID))
		exists := existingErr == nil
		if existingErr != nil && !errors.Is(existingErr, pgx.ErrNoRows) {
			return existingErr
		}
		if exists {
			store.PreparePlanningBundleRevision(existing, &bundle)
		}
		if err := store.ValidatePlanningBundleShape(&bundle); err != nil {
			return err
		}
		if exists && store.PlanningBundleContentEqual(existing, bundle) {
			result = existing
			return nil
		}
		if exists && existing.Status != core.PlanningBundlePending {
			return &store.PlanningBundleConflictError{Message: fmt.Sprintf("planning bundle %s is %s", bundle.ID, existing.Status)}
		}
		for i := range bundle.Documents {
			doc := &bundle.Documents[i]
			switch doc.Kind {
			case core.PlanningBundleRequirement:
				var confirmed bool
				if err := tx.QueryRow(ctx, `SELECT r.title,v.confirmed FROM requirement_versions v JOIN requirements r ON r.workspace_id=v.workspace_id AND r.id=v.requirement_id WHERE v.workspace_id=$1 AND v.requirement_id=$2 AND v.version=$3`, bundle.Workspace, doc.ID, doc.Version).Scan(&doc.Title, &confirmed); err != nil {
					return notFound(err, "requirement %s version %d", doc.ID, doc.Version)
				}
				if confirmed {
					return fmt.Errorf("requirement %s version %d is not pending", doc.ID, doc.Version)
				}
			case core.PlanningBundleSystemDesign:
				var confirmed, dismissed bool
				if err := tx.QueryRow(ctx, `SELECT d.title,v.confirmed,v.dismissed FROM system_design_versions v JOIN system_designs d ON d.workspace_id=v.workspace_id AND d.id=v.document_id WHERE v.workspace_id=$1 AND v.document_id=$2 AND v.version=$3`, bundle.Workspace, doc.ID, doc.Version).Scan(&doc.Title, &confirmed, &dismissed); err != nil {
					return notFound(err, "system design %s version %d", doc.ID, doc.Version)
				}
				if confirmed || dismissed {
					return fmt.Errorf("system design %s version %d is not pending", doc.ID, doc.Version)
				}
			case core.PlanningBundleDecision:
				var status string
				if err := tx.QueryRow(ctx, `SELECT statement,status FROM decisions WHERE workspace_id=$1 AND id=$2`, bundle.Workspace, doc.ID).Scan(&doc.Title, &status); err != nil {
					return notFound(err, "decision %s", doc.ID)
				}
				if status != string(core.DecisionProposed) {
					return fmt.Errorf("decision %s is not pending", doc.ID)
				}
			}
			doc.Status = "pending"
		}
		if _, validationErr := validatePlanningBundleContextsTx(ctx, tx, bundle); validationErr != nil {
			return validationErr
		}
		bundle.Status, bundle.CreatedBy = core.PlanningBundlePending, actor.ID
		if exists {
			bundle.CreatedAt, bundle.CreatedBy = existing.CreatedAt, existing.CreatedBy
		} else if bundle.CreatedAt.IsZero() {
			bundle.CreatedAt = time.Now().UTC()
		}
		documents, marshalErr := json.Marshal(bundle.Documents)
		if marshalErr != nil {
			return marshalErr
		}
		tasks, marshalErr := json.Marshal(bundle.Tasks)
		if marshalErr != nil {
			return marshalErr
		}
		kind, at := store.PlanningBundleFinalized, bundle.CreatedAt
		payload := map[string]any{"workspace_id": bundle.Workspace, "bundle_id": bundle.ID, "session_id": bundle.SessionID, "documents": bundle.Documents, "tasks": bundle.Tasks}
		if exists {
			if _, updateErr := tx.Exec(ctx, `UPDATE planning_bundles SET session_id=$3,title=$4,documents=$5,tasks=$6 WHERE workspace_id=$1 AND id=$2`, bundle.Workspace, bundle.ID, bundle.SessionID, bundle.Title, documents, tasks); updateErr != nil {
				return updateErr
			}
			kind, at = store.PlanningBundleRevised, time.Now().UTC()
			payload["previous_documents"], payload["previous_tasks"] = existing.Documents, existing.Tasks
		} else if _, insertErr := tx.Exec(ctx, `INSERT INTO planning_bundles (workspace_id,id,session_id,title,documents,tasks,status,created_by,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,NULLIF($8,''),$9)`, bundle.Workspace, bundle.ID, bundle.SessionID, bundle.Title, documents, tasks, string(bundle.Status), bundle.CreatedBy, bundle.CreatedAt); insertErr != nil {
			return insertErr
		}
		if eventErr := insertWorkspaceEvent(ctx, q, core.Event{Kind: kind, At: at, Payload: core.JSONPayload(payload)}); eventErr != nil {
			return eventErr
		}
		result = bundle
		return nil
	})
	if err != nil {
		return core.PlanningBundle{}, err
	}
	return result, nil
}

type bundleContextVersions struct {
	designs             map[string]int
	pendingRequirements map[string]int
	pendingDesigns      map[string]int
	activeRequirements  map[string]int
	activeDesigns       map[string]int
}

func validatePlanningBundleContextsTx(ctx context.Context, tx pgx.Tx, bundle core.PlanningBundle) (map[string]bundleContextVersions, error) {
	pendingRequirements, pendingDesigns := map[string]int{}, map[string]int{}
	for _, document := range bundle.Documents {
		switch document.Kind {
		case core.PlanningBundleRequirement:
			pendingRequirements[document.ID] = document.Version
		case core.PlanningBundleSystemDesign:
			pendingDesigns[document.ID] = document.Version
		}
	}
	result := map[string]bundleContextVersions{}
	for _, member := range bundle.Tasks {
		versions := bundleContextVersions{designs: map[string]int{}, pendingRequirements: map[string]int{}, pendingDesigns: map[string]int{}, activeRequirements: map[string]int{}, activeDesigns: map[string]int{}}
		for _, id := range member.Context.RequirementIDs {
			if version := pendingRequirements[id]; version > 0 {
				versions.pendingRequirements[id] = version
				var confirmed bool
				if err := tx.QueryRow(ctx, `SELECT confirmed FROM requirement_versions WHERE workspace_id=$1 AND requirement_id=$2 AND version=$3`, bundle.Workspace, id, version).Scan(&confirmed); err != nil {
					return nil, notFound(err, "requirement %s version %d", id, version)
				}
				if confirmed {
					versions.activeRequirements[id] = version
				}
				continue
			}
			if _, err := validateTaskContextTx(ctx, tx, bundle.Workspace, store.TaskContextInput{RequirementIDs: []string{id}}); err != nil {
				return nil, err
			}
		}
		for _, id := range member.Context.DesignIDs {
			if version := pendingDesigns[id]; version > 0 {
				versions.designs[id], versions.pendingDesigns[id] = version, version
				var confirmed bool
				if err := tx.QueryRow(ctx, `SELECT confirmed FROM system_design_versions WHERE workspace_id=$1 AND document_id=$2 AND version=$3`, bundle.Workspace, id, version).Scan(&confirmed); err != nil {
					return nil, notFound(err, "system design %s version %d", id, version)
				}
				if confirmed {
					versions.activeDesigns[id] = version
				}
				continue
			}
			confirmed, err := validateTaskContextTx(ctx, tx, bundle.Workspace, store.TaskContextInput{DesignIDs: []string{id}})
			if err != nil {
				return nil, err
			}
			versions.designs[id] = confirmed[id]
		}
		result[member.MemberID] = versions
	}
	return result, nil
}

func scanPlanningBundle(row pgx.Row) (core.PlanningBundle, error) {
	var b core.PlanningBundle
	var docs, tasks []byte
	var status string
	var decided *time.Time
	err := row.Scan(&b.ID, &b.SessionID, &b.Title, &docs, &tasks, &status, &b.CreatedBy, &b.DecidedBy, &b.CreatedAt, &decided, &b.Workspace)
	if err != nil {
		return b, err
	}
	if err = json.Unmarshal(docs, &b.Documents); err != nil {
		return b, err
	}
	if err = json.Unmarshal(tasks, &b.Tasks); err != nil {
		return b, err
	}
	b.Status = core.PlanningBundleStatus(status)
	if decided != nil {
		b.DecidedAt = *decided
	}
	return b, nil
}

func (s *Store) GetPlanningBundle(ctx context.Context, id string) (core.PlanningBundle, error) {
	b, err := scanPlanningBundle(s.pool.QueryRow(ctx, planningBundleSelect+` WHERE workspace_id=$1 AND id=$2`, workspace(ctx), id))
	if errors.Is(err, pgx.ErrNoRows) {
		return core.PlanningBundle{}, fmt.Errorf("planning bundle %s: %w", id, store.ErrNotFound)
	}
	return b, err
}

func (s *Store) ListPlanningBundles(ctx context.Context) ([]core.PlanningBundle, error) {
	rows, err := s.pool.Query(ctx, planningBundleSelect+` WHERE workspace_id=$1 ORDER BY created_at DESC,id`, workspace(ctx))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []core.PlanningBundle{}
	for rows.Next() {
		b, scanErr := scanPlanningBundle(rows)
		if scanErr != nil {
			return nil, scanErr
		}
		out = append(out, b)
	}
	return out, rows.Err()
}

func (s *Store) ApprovePlanningBundle(ctx context.Context, id string) (core.PlanningBundle, error) {
	var result core.PlanningBundle
	err := s.inTx(ctx, func(tx pgx.Tx, q *db.Queries) error {
		bundle, err := scanPlanningBundle(tx.QueryRow(ctx, planningBundleSelect+` WHERE workspace_id=$1 AND id=$2 FOR UPDATE`, workspace(ctx), id))
		if err != nil {
			return notFound(err, "planning bundle %s", id)
		}
		if bundle.Status == core.PlanningBundleApproved {
			result = bundle
			return nil
		}
		if bundle.Status != core.PlanningBundlePending {
			return &store.PlanningBundleConflictError{Message: fmt.Sprintf("planning bundle %s is %s", id, bundle.Status)}
		}
		if err = lockDependencyEdgesTx(ctx, tx, bundle.Workspace); err != nil {
			return err
		}
		byMember := map[string]core.PlanningBundleTask{}
		for _, member := range bundle.Tasks {
			byMember[member.MemberID] = member
			var exists bool
			if err = tx.QueryRow(ctx, `SELECT EXISTS(SELECT 1 FROM tasks WHERE workspace_id=$1 AND id=$2)`, bundle.Workspace, member.CreatedTaskID).Scan(&exists); err != nil {
				return err
			}
			if exists {
				return &store.PlanningBundleConflictError{Message: fmt.Sprintf("bundle task identity %s already exists", member.CreatedTaskID)}
			}
		}
		contextVersions, validationErr := validatePlanningBundleContextsTx(ctx, tx, bundle)
		if validationErr != nil {
			return validationErr
		}
		now := time.Now().UTC()
		for _, member := range bundle.Tasks {
			task := core.Task{ID: member.CreatedTaskID, Workspace: bundle.Workspace, Source: "planning_bundle:" + bundle.ID + ":" + member.MemberID, IntakeKey: "planning-bundle:" + bundle.ID + ":" + member.MemberID, Title: member.Title, Body: member.Body, Level: core.L2, SpecApproval: member.SpecApproval, MergeApproval: member.MergeApproval, PolicyVersion: 1, SetupContract: member.SetupContract, Repo: member.Repo, BaseBranch: member.BaseBranch, Branch: gitx.BranchName(member.CreatedTaskID), State: core.TaskQueued, NextStage: core.StageTriage, CreatedAt: now}
			if _, err = q.InsertTask(ctx, taskInsertParams(task)); err != nil {
				return err
			}
			if _, err = insertEventWithID(ctx, q, core.Event{TaskID: task.ID, Kind: "task.created", Payload: core.JSONPayload(task), At: now}); err != nil {
				return err
			}
		}
		for _, member := range bundle.Tasks {
			for _, dep := range member.DependsOn {
				dependencyID := byMember[dep].CreatedTaskID
				if _, err = tx.Exec(ctx, `INSERT INTO task_dependencies (workspace_id,task_id,depends_on_task_id) VALUES ($1,$2,$3)`, bundle.Workspace, member.CreatedTaskID, dependencyID); err != nil {
					return err
				}
				if err = insertEvent(ctx, q, core.Event{TaskID: member.CreatedTaskID, Kind: "task.dependency_added", At: now, Payload: core.JSONPayload(map[string]string{"task_id": member.CreatedTaskID, "depends_on_task_id": dependencyID})}); err != nil {
					return err
				}
			}
			for _, reqID := range member.Context.RequirementIDs {
				payload := map[string]any{"id": reqID}
				if pending := contextVersions[member.MemberID].pendingRequirements[reqID]; pending > 0 {
					payload["pending_version"], payload["unconfirmed"] = pending, true
				}
				if err = insertEvent(ctx, q, core.Event{TaskID: member.CreatedTaskID, Kind: store.TaskContextRequirementAdded, At: now, Payload: core.JSONPayload(payload)}); err != nil {
					return err
				}
				if version := contextVersions[member.MemberID].activeRequirements[reqID]; version > 0 {
					if err = insertEvent(ctx, q, core.Event{TaskID: member.CreatedTaskID, Kind: store.TaskContextRequirementActive, At: now, Payload: core.JSONPayload(map[string]any{"id": reqID, "version": version})}); err != nil {
						return err
					}
				}
			}
			for _, designID := range member.Context.DesignIDs {
				payload := map[string]any{"id": designID, "version": contextVersions[member.MemberID].designs[designID]}
				if contextVersions[member.MemberID].pendingDesigns[designID] > 0 {
					payload["unconfirmed"] = true
				}
				if err = insertEvent(ctx, q, core.Event{TaskID: member.CreatedTaskID, Kind: store.TaskContextDesignAdded, At: now, Payload: core.JSONPayload(payload)}); err != nil {
					return err
				}
				if version := contextVersions[member.MemberID].activeDesigns[designID]; version > 0 {
					if err = insertEvent(ctx, q, core.Event{TaskID: member.CreatedTaskID, Kind: store.TaskContextDesignActive, At: now, Payload: core.JSONPayload(map[string]any{"id": designID, "version": version})}); err != nil {
						return err
					}
				}
			}
		}
		actor := store.ActorFromContext(ctx)
		if _, err = tx.Exec(ctx, `UPDATE planning_bundles SET status='approved',decided_by=NULLIF($3,''),decided_at=$4 WHERE workspace_id=$1 AND id=$2`, bundle.Workspace, bundle.ID, actor.ID, now); err != nil {
			return err
		}
		ids := make([]string, len(bundle.Tasks))
		for i := range bundle.Tasks {
			ids[i] = bundle.Tasks[i].CreatedTaskID
		}
		if err = insertWorkspaceEvent(ctx, q, core.Event{Kind: store.PlanningBundleApproved, At: now, Payload: core.JSONPayload(map[string]any{"workspace_id": bundle.Workspace, "bundle_id": bundle.ID, "created_task_ids": ids})}); err != nil {
			return err
		}
		for _, taskID := range ids {
			if _, err = s.enqueueTaskTx(ctx, tx, taskID, bundle.Workspace); err != nil {
				return err
			}
		}
		bundle.Status, bundle.DecidedBy, bundle.DecidedAt = core.PlanningBundleApproved, actor.ID, now
		result = bundle
		return nil
	})
	return result, err
}

func (s *Store) RejectPlanningBundle(ctx context.Context, id string) (core.PlanningBundle, error) {
	var result core.PlanningBundle
	err := s.inTx(ctx, func(tx pgx.Tx, q *db.Queries) error {
		bundle, err := scanPlanningBundle(tx.QueryRow(ctx, planningBundleSelect+` WHERE workspace_id=$1 AND id=$2 FOR UPDATE`, workspace(ctx), id))
		if err != nil {
			return notFound(err, "planning bundle %s", id)
		}
		if bundle.Status == core.PlanningBundleRejected {
			result = bundle
			return nil
		}
		if bundle.Status != core.PlanningBundlePending {
			return &store.PlanningBundleConflictError{Message: fmt.Sprintf("planning bundle %s is %s", id, bundle.Status)}
		}
		now := time.Now().UTC()
		actor := store.ActorFromContext(ctx)
		if _, err = tx.Exec(ctx, `UPDATE planning_bundles SET status='rejected',decided_by=NULLIF($3,''),decided_at=$4 WHERE workspace_id=$1 AND id=$2`, bundle.Workspace, bundle.ID, actor.ID, now); err != nil {
			return err
		}
		if err = insertWorkspaceEvent(ctx, q, core.Event{Kind: store.PlanningBundleRejected, At: now, Payload: core.JSONPayload(map[string]any{"workspace_id": bundle.Workspace, "bundle_id": bundle.ID})}); err != nil {
			return err
		}
		bundle.Status, bundle.DecidedBy, bundle.DecidedAt = core.PlanningBundleRejected, actor.ID, now
		result = bundle
		return nil
	})
	return result, err
}
