package singlestore

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/go-sql-driver/mysql"
	"github.com/kidus-tiliksew/conveyor/internal/core"
	"github.com/kidus-tiliksew/conveyor/internal/eventlog/s2log"
	"github.com/kidus-tiliksew/conveyor/internal/gitx"
	"github.com/kidus-tiliksew/conveyor/internal/queue"
	"github.com/kidus-tiliksew/conveyor/internal/queue/logqueue"
	"github.com/kidus-tiliksew/conveyor/internal/store"
)

const planningBundleSelect = `SELECT id,session_id,title,documents,tasks,status,COALESCE(created_by,''),COALESCE(decided_by,''),created_at,decided_at,workspace_id FROM planning_bundles`

func (s *Store) CreatePlanningBundle(ctx context.Context, bundle core.PlanningBundle) (core.PlanningBundle, error) {
	bundle.Workspace = documentWorkspace(ctx)
	// Resolve the deterministic identity before the locked lookup. Full shape
	// validation follows identity adoption because a retry may omit the task IDs
	// generated by its first successful finalize.
	bundle.ID = strings.TrimSpace(bundle.ID)
	actor := store.ActorFromContext(ctx)
	var result core.PlanningBundle
	err := s.documentTx(ctx, func(tx *sql.Tx) error {
		if err := documentParent(ctx, tx, "planning_sessions", bundle.SessionID); err != nil {
			return err
		}

		existing, existingErr := scanPlanningBundle(documentRow(ctx, tx, planningBundleSelect+` WHERE workspace_id=? AND id=? FOR UPDATE`, bundle.Workspace, bundle.ID))
		exists := existingErr == nil
		if existingErr != nil && !errors.Is(existingErr, sql.ErrNoRows) {
			return existingErr
		}
		if exists {
			store.PreparePlanningBundleRevision(existing, &bundle)
		}
		if err := store.ValidatePlanningBundleShape(&bundle); err != nil {
			return err
		}
		if exists && store.PlanningBundleContentEqual(existing, bundle) {
			result = existing
			return nil
		}
		if exists && existing.Status != core.PlanningBundlePending {
			return &store.PlanningBundleConflictError{Message: fmt.Sprintf("planning bundle %s is %s", bundle.ID, existing.Status)}
		}
		for i := range bundle.Documents {
			doc := &bundle.Documents[i]
			switch doc.Kind {
			case core.PlanningBundleRequirement:
				var confirmed bool
				if err := documentRow(ctx, tx, `SELECT r.title,v.confirmed FROM requirement_versions v JOIN requirements r ON r.workspace_id=v.workspace_id AND r.id=v.requirement_id WHERE v.workspace_id=? AND v.requirement_id=? AND v.version=?`, bundle.Workspace, doc.ID, doc.Version).Scan(&doc.Title, &confirmed); err != nil {
					return notFound(err, "requirement %s version %d", doc.ID, doc.Version)
				}
				if confirmed {
					return fmt.Errorf("requirement %s version %d is not pending", doc.ID, doc.Version)
				}
			case core.PlanningBundleSystemDesign:
				var confirmed, dismissed bool
				if err := documentRow(ctx, tx, `SELECT d.title,v.confirmed,v.dismissed FROM system_design_versions v JOIN system_designs d ON d.workspace_id=v.workspace_id AND d.id=v.document_id WHERE v.workspace_id=? AND v.document_id=? AND v.version=?`, bundle.Workspace, doc.ID, doc.Version).Scan(&doc.Title, &confirmed, &dismissed); err != nil {
					return notFound(err, "system design %s version %d", doc.ID, doc.Version)
				}
				if confirmed || dismissed {
					return fmt.Errorf("system design %s version %d is not pending", doc.ID, doc.Version)
				}
			case core.PlanningBundleDecision:
				var status string
				if err := documentRow(ctx, tx, `SELECT statement,status FROM decisions WHERE workspace_id=? AND id=?`, bundle.Workspace, doc.ID).Scan(&doc.Title, &status); err != nil {
					return notFound(err, "decision %s", doc.ID)
				}
				if status != string(core.DecisionProposed) {
					return fmt.Errorf("decision %s is not pending", doc.ID)
				}
			}
			doc.Status = "pending"
		}
		if _, validationErr := validatePlanningBundleContextsTx(ctx, tx, bundle); validationErr != nil {
			return validationErr
		}
		bundle.Status, bundle.CreatedBy = core.PlanningBundlePending, actor.ID
		if exists {
			bundle.CreatedAt, bundle.CreatedBy = existing.CreatedAt, existing.CreatedBy
		} else if bundle.CreatedAt.IsZero() {
			bundle.CreatedAt = time.Now().UTC()
		}
		documents, marshalErr := json.Marshal(bundle.Documents)
		if marshalErr != nil {
			return marshalErr
		}
		tasks, marshalErr := json.Marshal(bundle.Tasks)
		if marshalErr != nil {
			return marshalErr
		}
		kind, at := store.PlanningBundleFinalized, bundle.CreatedAt
		payload := map[string]any{"workspace_id": bundle.Workspace, "bundle_id": bundle.ID, "session_id": bundle.SessionID, "documents": bundle.Documents, "tasks": bundle.Tasks}
		if exists {
			if _, updateErr := documentExec(ctx, tx, `UPDATE planning_bundles SET session_id=?,title=?,documents=?,tasks=? WHERE workspace_id=? AND id=?`, bundle.SessionID, bundle.Title, documents, tasks, bundle.Workspace, bundle.ID); updateErr != nil {
				return updateErr
			}
			kind, at = store.PlanningBundleRevised, time.Now().UTC()
			payload["previous_documents"], payload["previous_tasks"] = existing.Documents, existing.Tasks
		} else if _, insertErr := documentExec(ctx, tx, `INSERT INTO planning_bundles (workspace_id,id,session_id,title,documents,tasks,status,created_by,created_at) VALUES (?,?,?,?,?,?,?,NULLIF(?,''),?)`, bundle.Workspace, bundle.ID, bundle.SessionID, bundle.Title, documents, tasks, string(bundle.Status), bundle.CreatedBy, bundle.CreatedAt); insertErr != nil {
			return insertErr
		}
		if eventErr := insertWorkspaceEvent(ctx, tx, core.Event{Kind: kind, At: at, Payload: core.JSONPayload(payload)}); eventErr != nil {
			return eventErr
		}
		result = bundle
		return nil
	})
	if err != nil {
		return core.PlanningBundle{}, err
	}
	return result, nil
}

type bundleContextVersions struct {
	designs             map[string]int
	pendingRequirements map[string]int
	pendingDesigns      map[string]int
	activeRequirements  map[string]int
	activeDesigns       map[string]int
}

func validatePlanningBundleContextsTx(ctx context.Context, tx *sql.Tx, bundle core.PlanningBundle) (map[string]bundleContextVersions, error) {
	pendingRequirements, pendingDesigns := map[string]int{}, map[string]int{}
	for _, document := range bundle.Documents {
		switch document.Kind {
		case core.PlanningBundleRequirement:
			pendingRequirements[document.ID] = document.Version
		case core.PlanningBundleSystemDesign:
			pendingDesigns[document.ID] = document.Version
		}
	}
	result := map[string]bundleContextVersions{}
	for _, member := range bundle.Tasks {
		versions := bundleContextVersions{designs: map[string]int{}, pendingRequirements: map[string]int{}, pendingDesigns: map[string]int{}, activeRequirements: map[string]int{}, activeDesigns: map[string]int{}}
		for _, id := range member.Context.RequirementIDs {
			if version := pendingRequirements[id]; version > 0 {
				versions.pendingRequirements[id] = version
				var confirmed bool
				if err := documentRow(ctx, tx, `SELECT confirmed FROM requirement_versions WHERE workspace_id=? AND requirement_id=? AND version=?`, bundle.Workspace, id, version).Scan(&confirmed); err != nil {
					return nil, notFound(err, "requirement %s version %d", id, version)
				}
				if confirmed {
					versions.activeRequirements[id] = version
				}
				continue
			}
			if _, err := validateTaskContextTx(ctx, tx, bundle.Workspace, store.TaskContextInput{RequirementIDs: []string{id}}); err != nil {
				return nil, err
			}
		}
		for _, id := range member.Context.DesignIDs {
			if version := pendingDesigns[id]; version > 0 {
				versions.designs[id], versions.pendingDesigns[id] = version, version
				var confirmed bool
				if err := documentRow(ctx, tx, `SELECT confirmed FROM system_design_versions WHERE workspace_id=? AND document_id=? AND version=?`, bundle.Workspace, id, version).Scan(&confirmed); err != nil {
					return nil, notFound(err, "system design %s version %d", id, version)
				}
				if confirmed {
					versions.activeDesigns[id] = version
				}
				continue
			}
			confirmed, err := validateTaskContextTx(ctx, tx, bundle.Workspace, store.TaskContextInput{DesignIDs: []string{id}})
			if err != nil {
				return nil, err
			}
			versions.designs[id] = confirmed[id]
		}
		result[member.MemberID] = versions
	}
	return result, nil
}

func scanPlanningBundle(row documentScanner) (core.PlanningBundle, error) {
	var b core.PlanningBundle
	var docs, tasks []byte
	var status string
	var decided *time.Time
	err := row.Scan(&b.ID, &b.SessionID, &b.Title, &docs, &tasks, &status, &b.CreatedBy, &b.DecidedBy, &b.CreatedAt, &decided, &b.Workspace)
	if err != nil {
		return b, err
	}
	if err = json.Unmarshal(docs, &b.Documents); err != nil {
		return b, err
	}
	if err = json.Unmarshal(tasks, &b.Tasks); err != nil {
		return b, err
	}
	b.Status = core.PlanningBundleStatus(status)
	if decided != nil {
		b.DecidedAt = *decided
	}
	return b, nil
}

func (s *Store) GetPlanningBundle(ctx context.Context, id string) (core.PlanningBundle, error) {
	b, err := scanPlanningBundle(documentRow(ctx, s.db, planningBundleSelect+` WHERE workspace_id=? AND id=?`, documentWorkspace(ctx), id))
	if errors.Is(err, sql.ErrNoRows) {
		return core.PlanningBundle{}, fmt.Errorf("planning bundle %s: %w", id, store.ErrNotFound)
	}
	return b, err
}

func (s *Store) ListPlanningBundles(ctx context.Context) ([]core.PlanningBundle, error) {
	rows, err := documentRows(ctx, s.db, planningBundleSelect+` WHERE workspace_id=? ORDER BY created_at DESC,id`, documentWorkspace(ctx))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []core.PlanningBundle{}
	for rows.Next() {
		b, scanErr := scanPlanningBundle(rows)
		if scanErr != nil {
			return nil, scanErr
		}
		out = append(out, b)
	}
	return out, rows.Err()
}

func (s *Store) ApprovePlanningBundle(ctx context.Context, id string) (core.PlanningBundle, error) {
	var result core.PlanningBundle
	err := s.documentTx(ctx, func(tx *sql.Tx) error {
		bundle, err := scanPlanningBundle(documentRow(ctx, tx, planningBundleSelect+` WHERE workspace_id=? AND id=? FOR UPDATE`, documentWorkspace(ctx), id))
		if err != nil {
			return notFound(err, "planning bundle %s", id)
		}
		if bundle.Status == core.PlanningBundleApproved {
			result = bundle
			return nil
		}
		if bundle.Status != core.PlanningBundlePending {
			return &store.PlanningBundleConflictError{Message: fmt.Sprintf("planning bundle %s is %s", id, bundle.Status)}
		}
		if err = lockDependencyEdgesTx(ctx, tx, bundle.Workspace); err != nil {
			return err
		}
		byMember := map[string]core.PlanningBundleTask{}
		for _, member := range bundle.Tasks {
			byMember[member.MemberID] = member
			var exists bool
			if err = documentRow(ctx, tx, `SELECT EXISTS(SELECT 1 FROM tasks WHERE workspace_id=? AND id=?)`, bundle.Workspace, member.CreatedTaskID).Scan(&exists); err != nil {
				return err
			}
			if exists {
				return &store.PlanningBundleConflictError{Message: fmt.Sprintf("bundle task identity %s already exists", member.CreatedTaskID)}
			}
		}
		contextVersions, validationErr := validatePlanningBundleContextsTx(ctx, tx, bundle)
		if validationErr != nil {
			return validationErr
		}
		now := time.Now().UTC()
		for _, member := range bundle.Tasks {
			task := core.Task{ID: member.CreatedTaskID, Workspace: bundle.Workspace, Source: "planning_bundle:" + bundle.ID + ":" + member.MemberID, IntakeKey: "planning-bundle:" + bundle.ID + ":" + member.MemberID, Title: member.Title, Body: member.Body, Level: core.L2, SpecApproval: member.SpecApproval, MergeApproval: member.MergeApproval, PolicyVersion: 1, SetupContract: member.SetupContract, Repo: member.Repo, BaseBranch: member.BaseBranch, Branch: gitx.BranchName(member.CreatedTaskID), State: core.TaskQueued, NextStage: core.StageTriage, CreatedAt: now}
			if _, err = insertPlanningBundleTask(ctx, tx, task); err != nil {
				return err
			}
			if _, err = insertEventWithID(ctx, tx, core.Event{TaskID: task.ID, Kind: "task.created", Payload: core.JSONPayload(task), At: now}); err != nil {
				return err
			}
		}
		for _, member := range bundle.Tasks {
			for _, dep := range member.DependsOn {
				dependencyID := byMember[dep].CreatedTaskID
				if _, err = documentExec(ctx, tx, `INSERT INTO task_dependencies (workspace_id,task_id,depends_on_task_id) VALUES (?,?,?)`, bundle.Workspace, member.CreatedTaskID, dependencyID); err != nil {
					return err
				}
				if err = insertEvent(ctx, tx, core.Event{TaskID: member.CreatedTaskID, Kind: "task.dependency_added", At: now, Payload: core.JSONPayload(map[string]string{"task_id": member.CreatedTaskID, "depends_on_task_id": dependencyID})}); err != nil {
					return err
				}
			}
			for _, reqID := range member.Context.RequirementIDs {
				payload := map[string]any{"id": reqID}
				if pending := contextVersions[member.MemberID].pendingRequirements[reqID]; pending > 0 {
					payload["pending_version"], payload["unconfirmed"] = pending, true
				}
				if err = insertEvent(ctx, tx, core.Event{TaskID: member.CreatedTaskID, Kind: store.TaskContextRequirementAdded, At: now, Payload: core.JSONPayload(payload)}); err != nil {
					return err
				}
				if version := contextVersions[member.MemberID].activeRequirements[reqID]; version > 0 {
					if err = insertEvent(ctx, tx, core.Event{TaskID: member.CreatedTaskID, Kind: store.TaskContextRequirementActive, At: now, Payload: core.JSONPayload(map[string]any{"id": reqID, "version": version})}); err != nil {
						return err
					}
				}
			}
			for _, designID := range member.Context.DesignIDs {
				payload := map[string]any{"id": designID, "version": contextVersions[member.MemberID].designs[designID]}
				if contextVersions[member.MemberID].pendingDesigns[designID] > 0 {
					payload["unconfirmed"] = true
				}
				if err = insertEvent(ctx, tx, core.Event{TaskID: member.CreatedTaskID, Kind: store.TaskContextDesignAdded, At: now, Payload: core.JSONPayload(payload)}); err != nil {
					return err
				}
				if version := contextVersions[member.MemberID].activeDesigns[designID]; version > 0 {
					if err = insertEvent(ctx, tx, core.Event{TaskID: member.CreatedTaskID, Kind: store.TaskContextDesignActive, At: now, Payload: core.JSONPayload(map[string]any{"id": designID, "version": version})}); err != nil {
						return err
					}
				}
			}
		}
		actor := store.ActorFromContext(ctx)
		if _, err = documentExec(ctx, tx, `UPDATE planning_bundles SET status='approved',decided_by=NULLIF(?,''),decided_at=? WHERE workspace_id=? AND id=?`, actor.ID, now, bundle.Workspace, bundle.ID); err != nil {
			return err
		}
		ids := make([]string, len(bundle.Tasks))
		for i := range bundle.Tasks {
			ids[i] = bundle.Tasks[i].CreatedTaskID
		}
		if err = insertWorkspaceEvent(ctx, tx, core.Event{Kind: store.PlanningBundleApproved, At: now, Payload: core.JSONPayload(map[string]any{"workspace_id": bundle.Workspace, "bundle_id": bundle.ID, "created_task_ids": ids})}); err != nil {
			return err
		}
		for _, taskID := range ids {
			if _, err = s.enqueueTaskTx(ctx, tx, taskID, bundle.Workspace); err != nil {
				return err
			}
		}
		bundle.Status, bundle.DecidedBy, bundle.DecidedAt = core.PlanningBundleApproved, actor.ID, now
		result = bundle
		return nil
	})
	return result, err
}

func (s *Store) RejectPlanningBundle(ctx context.Context, id string) (core.PlanningBundle, error) {
	var result core.PlanningBundle
	err := s.documentTx(ctx, func(tx *sql.Tx) error {
		bundle, err := scanPlanningBundle(documentRow(ctx, tx, planningBundleSelect+` WHERE workspace_id=? AND id=? FOR UPDATE`, documentWorkspace(ctx), id))
		if err != nil {
			return notFound(err, "planning bundle %s", id)
		}
		if bundle.Status == core.PlanningBundleRejected {
			result = bundle
			return nil
		}
		if bundle.Status != core.PlanningBundlePending {
			return &store.PlanningBundleConflictError{Message: fmt.Sprintf("planning bundle %s is %s", id, bundle.Status)}
		}
		now := time.Now().UTC()
		actor := store.ActorFromContext(ctx)
		if _, err = documentExec(ctx, tx, `UPDATE planning_bundles SET status='rejected',decided_by=NULLIF(?,''),decided_at=? WHERE workspace_id=? AND id=?`, actor.ID, now, bundle.Workspace, bundle.ID); err != nil {
			return err
		}
		if err = insertWorkspaceEvent(ctx, tx, core.Event{Kind: store.PlanningBundleRejected, At: now, Payload: core.JSONPayload(map[string]any{"workspace_id": bundle.Workspace, "bundle_id": bundle.ID})}); err != nil {
			return err
		}
		bundle.Status, bundle.DecidedBy, bundle.DecidedAt = core.PlanningBundleRejected, actor.ID, now
		result = bundle
		return nil
	})
	return result, err
}

func (s *Store) proposeTaskContext(ctx context.Context, input core.TaskContextProposalInput, legacyCompatibility bool) (core.TaskContextProposal, bool, error) {
	input.TaskID, input.TargetID, input.Justification = strings.TrimSpace(input.TaskID), strings.TrimSpace(input.TargetID), strings.TrimSpace(input.Justification)
	if !input.Valid() {
		return core.TaskContextProposal{}, false, fmt.Errorf("invalid task context proposal")
	}
	var proposal core.TaskContextProposal
	var suppressed bool
	err := s.documentTx(ctx, func(tx *sql.Tx) error {
		var state string
		if err := documentRow(ctx, tx, `SELECT state FROM tasks WHERE workspace_id=? AND id=? FOR UPDATE`, documentWorkspace(ctx), input.TaskID).Scan(&state); err != nil {
			return notFound(err, "task %s", input.TaskID)
		}
		if core.TaskTerminal(core.TaskState(state)) && !legacyCompatibility {
			return store.ErrTaskTerminal
		}
		events, err := documentTaskEvents(ctx, tx, input.TaskID)
		if err != nil {
			return err
		}
		activeRequirements, activeDesigns := store.ActiveTaskContextReferences(events)
		if input.TargetKind == core.TaskContextProposalRequirement && activeRequirements[input.TargetID] ||
			input.TargetKind == core.TaskContextProposalSystemDesign && activeDesigns[input.TargetID] > 0 {
			suppressed = true
			return nil
		}
		if existing, getErr := getTaskContextProposalTx(ctx, tx, input.TaskID, input.TargetKind, input.TargetID, true); getErr == nil {
			if existing.State == core.TaskContextProposalProposed {
				proposal, suppressed = existing, true
				return nil
			}
			return fmt.Errorf("%w: cannot repropose a %s proposal", store.ErrTaskContextProposalTransition, existing.State)
		} else if !errors.Is(getErr, sql.ErrNoRows) {
			return getErr
		}
		var title, requirementSlug string
		var current *int
		var targetErr error
		if input.TargetKind == core.TaskContextProposalRequirement {
			targetErr = documentRow(ctx, tx, `SELECT title,slug,current_version FROM requirements WHERE workspace_id=? AND id=? FOR UPDATE`, documentWorkspace(ctx), input.TargetID).Scan(&title, &requirementSlug, &current)
		} else {
			targetErr = documentRow(ctx, tx, `SELECT title,current_version FROM system_designs WHERE workspace_id=? AND id=? FOR UPDATE`, documentWorkspace(ctx), input.TargetID).Scan(&title, &current)
		}
		if targetErr != nil {
			kind := string(input.TargetKind)
			if input.TargetKind == core.TaskContextProposalSystemDesign {
				kind = "system design"
			}
			if errors.Is(targetErr, sql.ErrNoRows) {
				return &store.TaskContextReferenceError{Kind: kind, ID: input.TargetID, Reason: "was not found in this workspace"}
			}
			return targetErr
		}
		if (current == nil || *current <= 0) && !legacyCompatibility {
			kind := string(input.TargetKind)
			if input.TargetKind == core.TaskContextProposalSystemDesign {
				kind = "system design"
			}
			return &store.TaskContextReferenceError{Kind: kind, ID: input.TargetID, Reason: "has no confirmed version"}
		}
		actor, now := store.ActorFromContext(ctx), time.Now().UTC()
		eventKind := "task.context_proposed"
		payload := map[string]any{"target_kind": input.TargetKind, "target_id": input.TargetID, "source": input.Source, "justification": input.Justification}
		if input.TargetKind == core.TaskContextProposalRequirement && legacyCompatibility {
			eventKind, payload["requirement_id"] = "task.requirement_suggested", input.TargetID
			payload["requirement_slug"], payload["requirement_title"] = requirementSlug, title
		}
		eventID, err := insertEventWithID(ctx, tx, core.Event{TaskID: input.TaskID, Kind: eventKind, At: now, Payload: core.JSONPayload(payload)})
		if err != nil {
			return err
		}
		_, err = documentExec(ctx, tx, `INSERT INTO task_context_proposals
			(workspace_id,task_id,target_kind,target_id,target_title,state,source,justification,created_by_event_id,proposed_by,created_at,updated_at)
			VALUES (?,?,?,?,?,'proposed',?,?,?,?,?,?)`, documentWorkspace(ctx), input.TaskID, input.TargetKind, input.TargetID, title, input.Source, input.Justification, eventID, actor.ID, now, now)
		if err != nil {
			return err
		}
		proposal, err = getTaskContextProposalTx(ctx, tx, input.TaskID, input.TargetKind, input.TargetID, true)
		return err
	})
	return proposal, suppressed, err
}

func (s *Store) transitionTaskContextProposal(ctx context.Context, taskID string, kind core.TaskContextProposalTargetKind, targetID string, target core.TaskContextProposalState, legacyCompatibility bool) (core.TaskContextProposal, error) {
	var proposal core.TaskContextProposal
	err := s.documentTx(ctx, func(tx *sql.Tx) error {
		var taskState string
		if err := documentRow(ctx, tx, `SELECT state FROM tasks WHERE workspace_id=? AND id=? FOR UPDATE`, documentWorkspace(ctx), taskID).Scan(&taskState); err != nil {
			return notFound(err, "task %s", taskID)
		}
		if core.TaskTerminal(core.TaskState(taskState)) && !legacyCompatibility {
			return store.ErrTaskTerminal
		}
		var err error
		proposal, err = getTaskContextProposalTx(ctx, tx, taskID, kind, strings.TrimSpace(targetID), true)
		if errors.Is(err, sql.ErrNoRows) {
			return fmt.Errorf("task context proposal: %w", store.ErrNotFound)
		}
		if err != nil {
			return err
		}
		if proposal.State == target {
			return nil
		}
		if proposal.State != core.TaskContextProposalProposed {
			return fmt.Errorf("%w: cannot transition %s proposal to %s", store.ErrTaskContextProposalTransition, proposal.State, target)
		}
		actor, now := store.ActorFromContext(ctx), time.Now().UTC()
		eventKind := "task.context_proposal_dismissed"
		if target == core.TaskContextProposalConfirmed {
			eventKind = "task.context_proposal_confirmed"
		}
		payload := map[string]any{"target_kind": kind, "target_id": targetID}
		if kind == core.TaskContextProposalRequirement && legacyCompatibility {
			payload["requirement_id"] = targetID
			if target == core.TaskContextProposalConfirmed {
				eventKind = "requirement.serves_confirmed"
			} else {
				eventKind = "requirement.serves_dismissed"
			}
		}
		eventID, err := insertEventWithID(ctx, tx, core.Event{TaskID: taskID, Kind: eventKind, At: now, Payload: core.JSONPayload(payload)})
		if err != nil {
			return err
		}
		if target == core.TaskContextProposalConfirmed {
			events, listErr := documentTaskEvents(ctx, tx, taskID)
			if listErr != nil {
				return listErr
			}
			activeRequirements, activeDesigns := store.ActiveTaskContextReferences(events)
			if kind == core.TaskContextProposalRequirement {
				if !activeRequirements[targetID] {
					if err = insertEvent(ctx, tx, core.Event{TaskID: taskID, Kind: store.TaskContextRequirementAdded, At: now, Payload: core.JSONPayload(map[string]any{"id": targetID})}); err != nil {
						return err
					}
				}
			} else {
				if activeDesigns[targetID] == 0 {
					var version *int
					if err = documentRow(ctx, tx, `SELECT current_version FROM system_designs WHERE workspace_id=? AND id=? FOR UPDATE`, documentWorkspace(ctx), targetID).Scan(&version); err != nil {
						return err
					}
					if version == nil || *version <= 0 {
						return &store.TaskContextReferenceError{Kind: "system design", ID: targetID, Reason: "has no confirmed version"}
					}
					if err = insertEvent(ctx, tx, core.Event{TaskID: taskID, Kind: store.TaskContextDesignAdded, At: now, Payload: core.JSONPayload(map[string]any{"id": targetID, "version": *version})}); err != nil {
						return err
					}
				}
			}
		}
		_, err = documentExec(ctx, tx, `UPDATE task_context_proposals SET state=?,decision_event_id=?,decided_by=?,updated_at=?
			WHERE workspace_id=? AND task_id=? AND target_kind=? AND target_id=?`, target, eventID, actor.ID, now, documentWorkspace(ctx), taskID, kind, targetID)
		if err != nil {
			return err
		}
		proposal.State, proposal.DecisionEventID, proposal.DecidedBy, proposal.UpdatedAt = target, eventID, actor.ID, now
		return nil
	})
	return proposal, err
}

func scanTaskContextProposal(row proposalScanner) (core.TaskContextProposal, error) {
	var item core.TaskContextProposal
	var kind, state, source string
	err := row.Scan(&item.Workspace, &item.TaskID, &kind, &item.TargetID, &item.TargetTitle, &state, &source, &item.Justification,
		&item.CreatedByEventID, &item.DecisionEventID, &item.ProposedBy, &item.DecidedBy, &item.CreatedAt, &item.UpdatedAt)
	item.TargetKind, item.State, item.Source = core.TaskContextProposalTargetKind(kind), core.TaskContextProposalState(state), core.TaskContextProposalSource(source)
	return item, err
}

func getTaskContextProposalTx(ctx context.Context, tx *sql.Tx, taskID string, kind core.TaskContextProposalTargetKind, targetID string, lock bool) (core.TaskContextProposal, error) {
	query := taskContextProposalSelect + ` WHERE workspace_id=? AND task_id=? AND target_kind=? AND target_id=?`
	if lock {
		query += ` FOR UPDATE`
	}
	return scanTaskContextProposal(documentRow(ctx, tx, query, documentWorkspace(ctx), taskID, kind, targetID))
}

const taskContextProposalSelect = `SELECT workspace_id,task_id,target_kind,target_id,target_title,state,source,justification,
	created_by_event_id,COALESCE(decision_event_id,0),proposed_by,decided_by,created_at,updated_at FROM task_context_proposals`

type proposalScanner interface{ Scan(...any) error }

func activatePendingTaskContextTx(ctx context.Context, tx *sql.Tx, workspaceID, documentID string, version int, design bool) error {
	addedKind, removedKind, activeKind := store.TaskContextRequirementAdded, store.TaskContextRequirementRemoved, store.TaskContextRequirementActive
	if design {
		addedKind, removedKind, activeKind = store.TaskContextDesignAdded, store.TaskContextDesignRemoved, store.TaskContextDesignActive
	}
	rows, err := documentRows(ctx, tx, `SELECT task_id,kind,payload_json FROM events
		WHERE workspace_id=? AND task_id IS NOT NULL AND kind IN (?,?)
		  AND JSON_EXTRACT_STRING(payload_json,'id')=? ORDER BY task_id,id`, workspaceID, addedKind, removedKind, documentID)
	if err != nil {
		return err
	}
	byTask := map[string][]core.Event{}
	for rows.Next() {
		var taskID, kind string
		var payload json.RawMessage
		if err = rows.Scan(&taskID, &kind, &payload); err != nil {
			rows.Close()
			return err
		}
		byTask[taskID] = append(byTask[taskID], core.Event{TaskID: taskID, Kind: kind, Payload: payload})
	}
	if err = rows.Err(); err != nil {
		rows.Close()
		return err
	}
	rows.Close()
	for taskID, events := range byTask {
		if !store.PendingTaskContextAttachment(events, documentID, version, design) {
			continue
		}
		if err = insertEvent(ctx, tx, core.Event{TaskID: taskID, Kind: activeKind,
			Payload: core.JSONPayload(map[string]any{"id": documentID, "version": version})}); err != nil {
			return err
		}
	}
	return nil
}

func validateTaskContextTx(ctx context.Context, tx *sql.Tx, workspaceID string, input store.TaskContextInput) (map[string]int, error) {
	for _, id := range input.RequirementIDs {
		var current sql.NullInt32
		var archivedAt *time.Time
		err := documentRow(ctx, tx, `SELECT current_version,archived_at FROM requirements WHERE workspace_id=? AND id=?`, workspaceID, id).Scan(&current, &archivedAt)
		if errors.Is(err, sql.ErrNoRows) {
			return nil, &store.TaskContextReferenceError{Kind: "requirement", ID: id, Reason: "was not found in this workspace"}
		}
		if err != nil {
			return nil, err
		}
		if !current.Valid || current.Int32 <= 0 {
			return nil, &store.TaskContextReferenceError{Kind: "requirement", ID: id, Reason: "has no confirmed version"}
		}
		if archivedAt != nil {
			return nil, &store.RequirementArchivedError{RequirementID: id}
		}
	}
	versions := map[string]int{}
	for _, id := range input.DesignIDs {
		var current sql.NullInt32
		var archivedAt *time.Time
		err := documentRow(ctx, tx, `SELECT current_version,archived_at FROM system_designs WHERE workspace_id=? AND id=?`, workspaceID, id).Scan(&current, &archivedAt)
		if errors.Is(err, sql.ErrNoRows) {
			return nil, &store.TaskContextReferenceError{Kind: "system design", ID: id, Reason: "was not found in this workspace"}
		}
		if err != nil {
			return nil, err
		}
		if !current.Valid || current.Int32 <= 0 {
			return nil, &store.TaskContextReferenceError{Kind: "system design", ID: id, Reason: "has no confirmed version"}
		}
		if archivedAt != nil {
			return nil, &store.SystemDesignArchivedError{DocumentID: id}
		}
		versions[id] = int(current.Int32)
	}
	return versions, nil
}
func (s *Store) withPlanningSessionLock(ctx context.Context, id string, fn func(context.Context) error) error {
	ws, err := workspace(ctx)
	if err != nil {
		return err
	}
	release, err := s.sessionLock(ctx, "planning-finalization:"+ws+":"+id)
	if err != nil {
		return err
	}
	defer release()
	return fn(ctx)
}
func (s *Store) WithPlanningSessionFinalization(ctx context.Context, id string, fn func(context.Context) error) error {
	return s.withPlanningSessionLock(ctx, id, func(ctx context.Context) error {
		session, err := s.GetPlanningSession(ctx, id)
		if err != nil {
			return err
		}
		if session.Status != core.PlanningSessionActive {
			return fmt.Errorf("planning session %s is %s and cannot produce an artifact", id, session.Status)
		}
		return fn(ctx)
	})
}
func (s *Store) enqueueTaskTx(ctx context.Context, tx *sql.Tx, taskID, ws string) (bool, error) {
	return logqueue.Enqueue(s2log.WithTx(ctx, tx), s.log, ws, queue.DispatchTaskArgs{}.Kind(), taskID, queue.DispatchTaskArgs{WorkspaceID: ws, TaskID: taskID}, queue.DispatchTaskMaxAttempts, time.Now().UTC())
}
func lockDependencyEdgesTx(ctx context.Context, tx *sql.Tx, ws string) error {
	return lockKey(ctx, tx, "dependency-edges:"+ws)
}
func insertPlanningBundleTask(ctx context.Context, tx *sql.Tx, t core.Task) (sql.Result, error) {
	setup, err := json.Marshal(t.SetupContract)
	if err != nil {
		return nil, err
	}
	return writeRow(ctx, tx, rowWrite{table: "tasks", operation: "INSERT", values: map[string]any{
		"workspace_id": t.Workspace, "id": t.ID, "source": t.Source, "mode": string(t.Mode), "intake_key": t.IntakeKey, "title": t.Title, "body": t.Body, "escalation_level": string(t.Level), "spec_approval": t.SpecApproval, "merge_approval": t.MergeApproval, "policy_version": t.PolicyVersion, "setup_contract": setup, "repo_name": t.Repo, "base_branch": t.BaseBranch, "branch": t.Branch, "state": string(t.State), "next_stage": string(t.NextStage), "created_at": t.CreatedAt,
	}})
}

func (s *Store) ListPendingProposals(ctx context.Context) ([]core.PendingProposal, error) {
	rows, err := documentRows(ctx, s.db, `
		SELECT proposal_id,title,tier,version,origin_type,origin_id,target_kind,justification,proposed_at
		FROM (
			SELECT v.document_id AS proposal_id,d.title,'system_design' AS tier,v.version,
				CASE WHEN v.origin_task_id IS NOT NULL THEN 'task' WHEN v.origin_session_id IS NOT NULL THEN 'session' ELSE 'operator' END AS origin_type,
				coalesce(v.origin_task_id,v.origin_session_id,'') AS origin_id,'' AS target_kind,'' AS justification,v.created_at AS proposed_at
			FROM system_design_versions v
			JOIN system_designs d ON d.workspace_id=v.workspace_id AND d.id=v.document_id
			WHERE v.workspace_id=? AND d.archived_at IS NULL AND NOT v.confirmed AND NOT v.dismissed
			UNION ALL
			SELECT v.requirement_id,r.title,'requirement' AS tier,v.version,
				CASE WHEN v.origin_task_id <> '' THEN 'task' WHEN v.origin_session_id <> '' THEN 'session' WHEN v.origin_drift_id <> '' THEN 'drift' ELSE v.origin END AS origin_type,
				coalesce(nullif(v.origin_task_id,''),nullif(v.origin_session_id,''),nullif(v.origin_drift_id,''),'') AS origin_id,'' AS target_kind,'' AS justification,v.created_at AS proposed_at
			FROM requirement_versions v
			JOIN requirements r ON r.workspace_id=v.workspace_id AND r.id=v.requirement_id
			WHERE v.workspace_id=? AND r.archived_at IS NULL AND NOT v.confirmed AND NOT v.retired
			  AND v.version > coalesce(r.current_version,0)
			UNION ALL
			SELECT d.id,d.statement,'decision' AS tier,NULL AS version,
				CASE WHEN d.origin_task_id IS NOT NULL THEN 'task' WHEN d.origin_session_id IS NOT NULL THEN 'session' ELSE 'operator' END AS origin_type,
				coalesce(d.origin_task_id,d.origin_session_id,'') AS origin_id,'' AS target_kind,'' AS justification,d.created_at AS proposed_at
			FROM decisions d
			WHERE d.workspace_id=? AND d.status='proposed'
			UNION ALL
			SELECT p.target_id,p.target_title,'task_context',NULL,'task',p.task_id,p.target_kind,p.justification,p.created_at
			FROM task_context_proposals p
			JOIN tasks t ON t.workspace_id=p.workspace_id AND t.id=p.task_id
			WHERE p.workspace_id=? AND p.state='proposed' AND t.state NOT IN ('merged','closed')
		) pending
		ORDER BY proposed_at,tier,proposal_id,version`, documentWorkspace(ctx), documentWorkspace(ctx), documentWorkspace(ctx), documentWorkspace(ctx))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := make([]core.PendingProposal, 0)
	for rows.Next() {
		var item core.PendingProposal
		var version *int
		if err = rows.Scan(&item.ID, &item.Title, &item.Tier, &version, &item.OriginType, &item.OriginID, &item.TargetKind, &item.Justification, &item.ProposedAt); err != nil {
			return nil, err
		}
		if version != nil {
			item.Version = *version
		}
		out = append(out, item)
	}
	return out, rows.Err()
}

func (s *Store) PendingProposalsProjection(ctx context.Context) (store.PendingProposalsProjection, error) {
	items, err := s.ListPendingProposals(ctx)
	result := store.PendingProposalsProjection{Items: items}
	if err != nil {
		return result, err
	}
	rows, err := documentRows(ctx, s.db, `SELECT t.id,t.state FROM tasks t WHERE t.workspace_id=? AND NOT EXISTS(SELECT 1 FROM tasks c WHERE c.workspace_id=t.workspace_id AND c.parent_task_id=t.id)`, documentWorkspace(ctx))
	if err != nil {
		return result, err
	}
	states := map[string]core.TaskState{}
	for rows.Next() {
		var id string
		var state core.TaskState
		if err = rows.Scan(&id, &state); err != nil {
			rows.Close()
			return result, err
		}
		states[id] = state
	}
	err = rows.Err()
	rows.Close()
	if err != nil || len(states) == 0 {
		return result, err
	}
	markers, err := s.ListActivityMarkers(ctx)
	if err != nil {
		return result, err
	}
	pendingContext, origins, authority := map[string]bool{}, map[string]bool{}, map[string]bool{}
	for _, p := range items {
		if p.OriginType == "task" {
			origins[p.OriginID] = true
			if p.Tier == "task_context" {
				pendingContext[p.OriginID] = true
			}
		}
	}
	rows, err = documentRows(ctx, s.db, `SELECT DISTINCT task_id FROM work_orders WHERE workspace_id=? AND ((stage='implement' AND state='submitted') OR (stage='review' AND state IN ('queued','claimed','submitted')))`, documentWorkspace(ctx))
	if err != nil {
		return result, err
	}
	for rows.Next() {
		var id string
		if err = rows.Scan(&id); err != nil {
			rows.Close()
			return result, err
		}
		authority[id] = origins[id]
	}
	err = rows.Err()
	rows.Close()
	if err != nil {
		return result, err
	}
	byID := map[string]store.ActivityMarker{}
	for _, m := range markers {
		byID[m.TaskID] = m
	}
	for id, state := range states {
		m := byID[id]
		if core.TaskTerminal(state) {
			m.Stalled = nil
		}
		if store.TaskNeedsAttention(core.Task{ID: id, State: state}, m, authority[id], pendingContext[id]) {
			result.TaskCount++
		}
	}
	return result, nil
}

// Acquisition is bounded independently of the callback lifetime. SingleStore
// can keep waiting on an INSERT/row lock despite a session lock_wait_timeout;
// canceling the acquisition query discards that connection and its transaction.
func (s *Store) WithPlanningSessionRun(ctx context.Context, id string, fn func(context.Context) error) error {
	ws, err := workspace(ctx)
	if err != nil {
		return err
	}
	acquireCtx, cancel := context.WithTimeout(ctx, time.Second)
	defer cancel()
	conn, err := s.db.Conn(acquireCtx)
	if err != nil {
		return planningRunAcquireError(ctx, acquireCtx, err)
	}
	defer conn.Close()
	// The parent context owns the transaction. Finishing acquisition must not
	// cancel a successfully claimed run while its callback is still working.
	tx, err := conn.BeginTx(ctx, nil)
	if err != nil {
		return translateBackendConflict(err)
	}
	defer tx.Rollback()
	if err = lockKey(acquireCtx, tx, fmt.Sprintf("planning-run:%d:%s:%s", len(ws), ws, id)); err != nil {
		return planningRunAcquireError(ctx, acquireCtx, err)
	}
	cancel()
	return fn(ctx)
}
func planningRunAcquireError(ctx, acquireCtx context.Context, err error) error {
	if ctx.Err() != nil {
		return ctx.Err()
	}
	var driverErr *mysql.MySQLError
	if acquireCtx.Err() != nil || errors.As(err, &driverErr) && driverErr.Number == 1205 {
		return store.ErrPlanningSessionRunConflict
	}
	return translateBackendConflict(err)
}

func documentParent(ctx context.Context, tx *sql.Tx, table, id string) error {
	if id == "" {
		return nil
	}
	switch table {
	case "requirements", "system_designs", "planning_sessions", "tasks", "artifacts", "planning_bundles":
	default:
		return fmt.Errorf("unsupported document parent")
	}
	var exists int
	err := documentRow(ctx, tx, "SELECT 1 FROM "+table+" WHERE workspace_id=? AND id=? FOR UPDATE", documentWorkspace(ctx), id).Scan(&exists)
	return notFound(err, "%s %s", table, id)
}

func (s *Store) listDocumentContextProposals(ctx context.Context) ([]core.TaskContextProposal, error) {
	rows, err := documentRows(ctx, s.db, taskContextProposalSelect+` WHERE workspace_id=? ORDER BY target_id,task_id,target_kind`, documentWorkspace(ctx))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []core.TaskContextProposal{}
	for rows.Next() {
		item, e := scanTaskContextProposal(rows)
		if e != nil {
			return nil, e
		}
		out = append(out, item)
	}
	return out, rows.Err()
}
