// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: control_plane.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveLatestSpecVersion = `-- name: ApproveLatestSpecVersion :one
UPDATE task_specs s
SET approved = true, approved_at = now()
FROM tasks t
WHERE s.task_id = t.id
  AND s.task_id = $1
  AND s.version = $2
  AND t.workspace_id = $3
  AND s.version = (SELECT MAX(version) FROM task_specs WHERE task_id = $1)
RETURNING s.task_id, s.version, s.content, s.acceptance_count, s.acceptance, s.decomposition, s.approved, s.created_at, s.approved_at, s.agent, s.model
`

type ApproveLatestSpecVersionParams struct {
	TaskID      string `json:"task_id"`
	Version     int32  `json:"version"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) ApproveLatestSpecVersion(ctx context.Context, arg ApproveLatestSpecVersionParams) (TaskSpec, error) {
	row := q.db.QueryRow(ctx, approveLatestSpecVersion, arg.TaskID, arg.Version, arg.WorkspaceID)
	var i TaskSpec
	err := row.Scan(
		&i.TaskID,
		&i.Version,
		&i.Content,
		&i.AcceptanceCount,
		&i.Acceptance,
		&i.Decomposition,
		&i.Approved,
		&i.CreatedAt,
		&i.ApprovedAt,
		&i.Agent,
		&i.Model,
	)
	return i, err
}

const bindTaskApproval = `-- name: BindTaskApproval :one
UPDATE tasks
SET reviewed_head_sha = $1,
    approved_head_sha = $1,
    approval_stale = false,
    refresh_baseline_sha = '', refresh_head_sha = '', refresh_review_scope = '',
    updated_at = now()
WHERE id = $2 AND workspace_id = $3
RETURNING id, workspace_id, source, title, body, class, escalation_level, repo_name, base_branch, branch, state, parent_task_id, created_at, updated_at, next_stage, recovery_stage, feature_id, intake_key, mode, spec_approval, merge_approval, policy_version, setup_name, setup_contract, hold, reviewed_head_sha, approved_head_sha, approval_stale, refresh_baseline_sha, refresh_head_sha, refresh_review_scope, origin_spec_version, origin_sub_id
`

type BindTaskApprovalParams struct {
	HeadSha     string `json:"head_sha"`
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) BindTaskApproval(ctx context.Context, arg BindTaskApprovalParams) (Task, error) {
	row := q.db.QueryRow(ctx, bindTaskApproval, arg.HeadSha, arg.ID, arg.WorkspaceID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Source,
		&i.Title,
		&i.Body,
		&i.Class,
		&i.EscalationLevel,
		&i.RepoName,
		&i.BaseBranch,
		&i.Branch,
		&i.State,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextStage,
		&i.RecoveryStage,
		&i.FeatureID,
		&i.IntakeKey,
		&i.Mode,
		&i.SpecApproval,
		&i.MergeApproval,
		&i.PolicyVersion,
		&i.SetupName,
		&i.SetupContract,
		&i.Hold,
		&i.ReviewedHeadSha,
		&i.ApprovedHeadSha,
		&i.ApprovalStale,
		&i.RefreshBaselineSha,
		&i.RefreshHeadSha,
		&i.RefreshReviewScope,
		&i.OriginSpecVersion,
		&i.OriginSubID,
	)
	return i, err
}

const countEvents = `-- name: CountEvents :one
SELECT count(*)::bigint FROM events e
JOIN tasks t ON t.id = e.task_id
WHERE e.task_id = $1 AND e.kind = $2 AND t.workspace_id = $3
`

type CountEventsParams struct {
	TaskID      pgtype.Text `json:"task_id"`
	Kind        string      `json:"kind"`
	WorkspaceID string      `json:"workspace_id"`
}

func (q *Queries) CountEvents(ctx context.Context, arg CountEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEvents, arg.TaskID, arg.Kind, arg.WorkspaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countEventsSinceHumanIntervention = `-- name: CountEventsSinceHumanIntervention :one
SELECT count(*)::bigint FROM events e
JOIN tasks t ON t.id = e.task_id
WHERE e.task_id = $1 AND e.kind = $2 AND t.workspace_id = $3
  AND e.at > COALESCE((
      SELECT max(i.at) FROM interventions i
      WHERE i.task_id = $1 AND i.actor_role = 'human'
  ), '-infinity'::timestamptz)
`

type CountEventsSinceHumanInterventionParams struct {
	TaskID      pgtype.Text `json:"task_id"`
	Kind        string      `json:"kind"`
	WorkspaceID string      `json:"workspace_id"`
}

// The §21.17 check-in window: events of a kind recorded after the latest
// human intervention on the task (all of them when no human has intervened).
func (q *Queries) CountEventsSinceHumanIntervention(ctx context.Context, arg CountEventsSinceHumanInterventionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsSinceHumanIntervention, arg.TaskID, arg.Kind, arg.WorkspaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getJob = `-- name: GetJob :one
SELECT j.id, j.task_id, j.stage, j.harness, j.model_tier, j.runner, j.pack_version, j.confinement_tier, j.cost_usd, j.tokens_in, j.tokens_out, j.state, j.started_at, j.ended_at, j.updated_at, j.auth_mode FROM jobs j
JOIN tasks t ON t.id = j.task_id
WHERE j.id = $1 AND t.workspace_id = $2
`

type GetJobParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, arg.ID, arg.WorkspaceID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Stage,
		&i.Harness,
		&i.ModelTier,
		&i.Runner,
		&i.PackVersion,
		&i.ConfinementTier,
		&i.CostUsd,
		&i.TokensIn,
		&i.TokensOut,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.UpdatedAt,
		&i.AuthMode,
	)
	return i, err
}

const getLatestJob = `-- name: GetLatestJob :one
SELECT j.id, j.task_id, j.stage, j.harness, j.model_tier, j.runner, j.pack_version, j.confinement_tier, j.cost_usd, j.tokens_in, j.tokens_out, j.state, j.started_at, j.ended_at, j.updated_at, j.auth_mode FROM jobs j
JOIN tasks t ON t.id = j.task_id
LEFT JOIN work_orders wo ON wo.job_id = j.id
WHERE j.task_id = $1 AND t.workspace_id = $2
ORDER BY COALESCE(j.started_at, wo.queue_entered_at) DESC, j.id DESC
LIMIT 1
`

type GetLatestJobParams struct {
	TaskID      string `json:"task_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetLatestJob(ctx context.Context, arg GetLatestJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, getLatestJob, arg.TaskID, arg.WorkspaceID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Stage,
		&i.Harness,
		&i.ModelTier,
		&i.Runner,
		&i.PackVersion,
		&i.ConfinementTier,
		&i.CostUsd,
		&i.TokensIn,
		&i.TokensOut,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.UpdatedAt,
		&i.AuthMode,
	)
	return i, err
}

const getLatestSpecVersion = `-- name: GetLatestSpecVersion :one
SELECT s.task_id, s.version, s.content, s.acceptance_count, s.acceptance, s.decomposition, s.approved, s.created_at, s.approved_at, s.agent, s.model FROM task_specs s
JOIN tasks t ON t.id = s.task_id
WHERE s.task_id = $1 AND t.workspace_id = $2
ORDER BY s.version DESC
LIMIT 1
`

type GetLatestSpecVersionParams struct {
	TaskID      string `json:"task_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetLatestSpecVersion(ctx context.Context, arg GetLatestSpecVersionParams) (TaskSpec, error) {
	row := q.db.QueryRow(ctx, getLatestSpecVersion, arg.TaskID, arg.WorkspaceID)
	var i TaskSpec
	err := row.Scan(
		&i.TaskID,
		&i.Version,
		&i.Content,
		&i.AcceptanceCount,
		&i.Acceptance,
		&i.Decomposition,
		&i.Approved,
		&i.CreatedAt,
		&i.ApprovedAt,
		&i.Agent,
		&i.Model,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, workspace_id, source, title, body, class, escalation_level, repo_name, base_branch, branch, state, parent_task_id, created_at, updated_at, next_stage, recovery_stage, feature_id, intake_key, mode, spec_approval, merge_approval, policy_version, setup_name, setup_contract, hold, reviewed_head_sha, approved_head_sha, approval_stale, refresh_baseline_sha, refresh_head_sha, refresh_review_scope, origin_spec_version, origin_sub_id FROM tasks WHERE id = $1 AND workspace_id = $2
`

type GetTaskParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.WorkspaceID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Source,
		&i.Title,
		&i.Body,
		&i.Class,
		&i.EscalationLevel,
		&i.RepoName,
		&i.BaseBranch,
		&i.Branch,
		&i.State,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextStage,
		&i.RecoveryStage,
		&i.FeatureID,
		&i.IntakeKey,
		&i.Mode,
		&i.SpecApproval,
		&i.MergeApproval,
		&i.PolicyVersion,
		&i.SetupName,
		&i.SetupContract,
		&i.Hold,
		&i.ReviewedHeadSha,
		&i.ApprovedHeadSha,
		&i.ApprovalStale,
		&i.RefreshBaselineSha,
		&i.RefreshHeadSha,
		&i.RefreshReviewScope,
		&i.OriginSpecVersion,
		&i.OriginSubID,
	)
	return i, err
}

const getTaskByIntakeKey = `-- name: GetTaskByIntakeKey :one
SELECT id, workspace_id, source, title, body, class, escalation_level, repo_name, base_branch, branch, state, parent_task_id, created_at, updated_at, next_stage, recovery_stage, feature_id, intake_key, mode, spec_approval, merge_approval, policy_version, setup_name, setup_contract, hold, reviewed_head_sha, approved_head_sha, approval_stale, refresh_baseline_sha, refresh_head_sha, refresh_review_scope, origin_spec_version, origin_sub_id FROM tasks WHERE workspace_id = $1 AND intake_key = $2
`

type GetTaskByIntakeKeyParams struct {
	WorkspaceID string      `json:"workspace_id"`
	IntakeKey   pgtype.Text `json:"intake_key"`
}

func (q *Queries) GetTaskByIntakeKey(ctx context.Context, arg GetTaskByIntakeKeyParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByIntakeKey, arg.WorkspaceID, arg.IntakeKey)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Source,
		&i.Title,
		&i.Body,
		&i.Class,
		&i.EscalationLevel,
		&i.RepoName,
		&i.BaseBranch,
		&i.Branch,
		&i.State,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextStage,
		&i.RecoveryStage,
		&i.FeatureID,
		&i.IntakeKey,
		&i.Mode,
		&i.SpecApproval,
		&i.MergeApproval,
		&i.PolicyVersion,
		&i.SetupName,
		&i.SetupContract,
		&i.Hold,
		&i.ReviewedHeadSha,
		&i.ApprovedHeadSha,
		&i.ApprovalStale,
		&i.RefreshBaselineSha,
		&i.RefreshHeadSha,
		&i.RefreshReviewScope,
		&i.OriginSpecVersion,
		&i.OriginSubID,
	)
	return i, err
}

const getTranscript = `-- name: GetTranscript :one
SELECT tr.job_id, tr.uri, tr.redaction_stats, tr.created_at FROM transcripts tr
JOIN jobs j ON j.id = tr.job_id
JOIN tasks t ON t.id = j.task_id
WHERE tr.job_id = $1 AND t.workspace_id = $2
`

type GetTranscriptParams struct {
	JobID       string `json:"job_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetTranscript(ctx context.Context, arg GetTranscriptParams) (Transcript, error) {
	row := q.db.QueryRow(ctx, getTranscript, arg.JobID, arg.WorkspaceID)
	var i Transcript
	err := row.Scan(
		&i.JobID,
		&i.Uri,
		&i.RedactionStats,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceConfig = `-- name: GetWorkspaceConfig :one
SELECT id, name, config_yaml, created_at, config_version FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspaceConfig(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceConfig, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ConfigYaml,
		&i.CreatedAt,
		&i.ConfigVersion,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (workspace_id, task_id, job_id, kind, actor_id, actor_role, payload_json, at)
SELECT t.workspace_id, $1, $2, $3,
       $4, $5, $6, $7
FROM tasks t
WHERE t.id = $1
RETURNING id, task_id, job_id, kind, actor_id, actor_role, payload_json, at, workspace_id
`

type InsertEventParams struct {
	TaskID      pgtype.Text        `json:"task_id"`
	JobID       pgtype.Text        `json:"job_id"`
	Kind        string             `json:"kind"`
	ActorID     string             `json:"actor_id"`
	ActorRole   string             `json:"actor_role"`
	PayloadJson []byte             `json:"payload_json"`
	At          pgtype.Timestamptz `json:"at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.TaskID,
		arg.JobID,
		arg.Kind,
		arg.ActorID,
		arg.ActorRole,
		arg.PayloadJson,
		arg.At,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.JobID,
		&i.Kind,
		&i.ActorID,
		&i.ActorRole,
		&i.PayloadJson,
		&i.At,
		&i.WorkspaceID,
	)
	return i, err
}

const insertIntervention = `-- name: InsertIntervention :one
INSERT INTO interventions (
    task_id, job_id, actor_id, actor_role, action, reason_code, comment, at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, task_id, job_id, actor_id, actor_role, action, reason_code, comment, at
`

type InsertInterventionParams struct {
	TaskID     string             `json:"task_id"`
	JobID      pgtype.Text        `json:"job_id"`
	ActorID    string             `json:"actor_id"`
	ActorRole  string             `json:"actor_role"`
	Action     string             `json:"action"`
	ReasonCode string             `json:"reason_code"`
	Comment    string             `json:"comment"`
	At         pgtype.Timestamptz `json:"at"`
}

func (q *Queries) InsertIntervention(ctx context.Context, arg InsertInterventionParams) (Intervention, error) {
	row := q.db.QueryRow(ctx, insertIntervention,
		arg.TaskID,
		arg.JobID,
		arg.ActorID,
		arg.ActorRole,
		arg.Action,
		arg.ReasonCode,
		arg.Comment,
		arg.At,
	)
	var i Intervention
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.JobID,
		&i.ActorID,
		&i.ActorRole,
		&i.Action,
		&i.ReasonCode,
		&i.Comment,
		&i.At,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO jobs (
    id, task_id, stage, harness, model_tier, auth_mode, runner,
    pack_version, confinement_tier, cost_usd, tokens_in,
    tokens_out, state, started_at, ended_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14, $15
)
RETURNING id, task_id, stage, harness, model_tier, runner, pack_version, confinement_tier, cost_usd, tokens_in, tokens_out, state, started_at, ended_at, updated_at, auth_mode
`

type InsertJobParams struct {
	ID              string             `json:"id"`
	TaskID          string             `json:"task_id"`
	Stage           string             `json:"stage"`
	Harness         string             `json:"harness"`
	ModelTier       string             `json:"model_tier"`
	AuthMode        string             `json:"auth_mode"`
	Runner          string             `json:"runner"`
	PackVersion     string             `json:"pack_version"`
	ConfinementTier string             `json:"confinement_tier"`
	CostUsd         pgtype.Float8      `json:"cost_usd"`
	TokensIn        int64              `json:"tokens_in"`
	TokensOut       int64              `json:"tokens_out"`
	State           string             `json:"state"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, insertJob,
		arg.ID,
		arg.TaskID,
		arg.Stage,
		arg.Harness,
		arg.ModelTier,
		arg.AuthMode,
		arg.Runner,
		arg.PackVersion,
		arg.ConfinementTier,
		arg.CostUsd,
		arg.TokensIn,
		arg.TokensOut,
		arg.State,
		arg.StartedAt,
		arg.EndedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Stage,
		&i.Harness,
		&i.ModelTier,
		&i.Runner,
		&i.PackVersion,
		&i.ConfinementTier,
		&i.CostUsd,
		&i.TokensIn,
		&i.TokensOut,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.UpdatedAt,
		&i.AuthMode,
	)
	return i, err
}

const insertSpecVersion = `-- name: InsertSpecVersion :one
INSERT INTO task_specs (
    task_id, version, content, acceptance_count, acceptance, decomposition,
    approved, approved_at, created_at, agent, model
)
SELECT
    $1,
    COALESCE(MAX(version), 0) + 1,
    $2,
    $3,
    $4,
    $5,
    false,
    NULL,
    $6,
    $7,
    $8
FROM task_specs
WHERE task_id = $1
RETURNING task_id, version, content, acceptance_count, acceptance, decomposition, approved, created_at, approved_at, agent, model
`

type InsertSpecVersionParams struct {
	TaskID          string             `json:"task_id"`
	Content         string             `json:"content"`
	AcceptanceCount int32              `json:"acceptance_count"`
	Acceptance      []byte             `json:"acceptance"`
	Decomposition   []byte             `json:"decomposition"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Agent           string             `json:"agent"`
	Model           string             `json:"model"`
}

func (q *Queries) InsertSpecVersion(ctx context.Context, arg InsertSpecVersionParams) (TaskSpec, error) {
	row := q.db.QueryRow(ctx, insertSpecVersion,
		arg.TaskID,
		arg.Content,
		arg.AcceptanceCount,
		arg.Acceptance,
		arg.Decomposition,
		arg.CreatedAt,
		arg.Agent,
		arg.Model,
	)
	var i TaskSpec
	err := row.Scan(
		&i.TaskID,
		&i.Version,
		&i.Content,
		&i.AcceptanceCount,
		&i.Acceptance,
		&i.Decomposition,
		&i.Approved,
		&i.CreatedAt,
		&i.ApprovedAt,
		&i.Agent,
		&i.Model,
	)
	return i, err
}

const insertTask = `-- name: InsertTask :one
INSERT INTO tasks (
    id, workspace_id, source, title, body, class, escalation_level, mode, hold, spec_approval, merge_approval, policy_version,
    setup_name, setup_contract, reviewed_head_sha, approved_head_sha, approval_stale,
    refresh_baseline_sha, refresh_head_sha, refresh_review_scope,
    repo_name, base_branch, branch, state, next_stage, recovery_stage, parent_task_id,
    origin_spec_version, origin_sub_id, feature_id, intake_key, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27,
    $28, $29,
    $30, $31, $32
)
RETURNING id, workspace_id, source, title, body, class, escalation_level, repo_name, base_branch, branch, state, parent_task_id, created_at, updated_at, next_stage, recovery_stage, feature_id, intake_key, mode, spec_approval, merge_approval, policy_version, setup_name, setup_contract, hold, reviewed_head_sha, approved_head_sha, approval_stale, refresh_baseline_sha, refresh_head_sha, refresh_review_scope, origin_spec_version, origin_sub_id
`

type InsertTaskParams struct {
	ID                 string             `json:"id"`
	WorkspaceID        string             `json:"workspace_id"`
	Source             string             `json:"source"`
	Title              string             `json:"title"`
	Body               string             `json:"body"`
	Class              string             `json:"class"`
	EscalationLevel    string             `json:"escalation_level"`
	Mode               string             `json:"mode"`
	Hold               bool               `json:"hold"`
	SpecApproval       bool               `json:"spec_approval"`
	MergeApproval      bool               `json:"merge_approval"`
	PolicyVersion      int32              `json:"policy_version"`
	SetupName          string             `json:"setup_name"`
	SetupContract      []byte             `json:"setup_contract"`
	ReviewedHeadSha    string             `json:"reviewed_head_sha"`
	ApprovedHeadSha    string             `json:"approved_head_sha"`
	ApprovalStale      bool               `json:"approval_stale"`
	RefreshBaselineSha string             `json:"refresh_baseline_sha"`
	RefreshHeadSha     string             `json:"refresh_head_sha"`
	RefreshReviewScope string             `json:"refresh_review_scope"`
	RepoName           string             `json:"repo_name"`
	BaseBranch         string             `json:"base_branch"`
	Branch             string             `json:"branch"`
	State              string             `json:"state"`
	NextStage          string             `json:"next_stage"`
	RecoveryStage      string             `json:"recovery_stage"`
	ParentTaskID       pgtype.Text        `json:"parent_task_id"`
	OriginSpecVersion  int32              `json:"origin_spec_version"`
	OriginSubID        string             `json:"origin_sub_id"`
	FeatureID          pgtype.Text        `json:"feature_id"`
	IntakeKey          pgtype.Text        `json:"intake_key"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, insertTask,
		arg.ID,
		arg.WorkspaceID,
		arg.Source,
		arg.Title,
		arg.Body,
		arg.Class,
		arg.EscalationLevel,
		arg.Mode,
		arg.Hold,
		arg.SpecApproval,
		arg.MergeApproval,
		arg.PolicyVersion,
		arg.SetupName,
		arg.SetupContract,
		arg.ReviewedHeadSha,
		arg.ApprovedHeadSha,
		arg.ApprovalStale,
		arg.RefreshBaselineSha,
		arg.RefreshHeadSha,
		arg.RefreshReviewScope,
		arg.RepoName,
		arg.BaseBranch,
		arg.Branch,
		arg.State,
		arg.NextStage,
		arg.RecoveryStage,
		arg.ParentTaskID,
		arg.OriginSpecVersion,
		arg.OriginSubID,
		arg.FeatureID,
		arg.IntakeKey,
		arg.CreatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Source,
		&i.Title,
		&i.Body,
		&i.Class,
		&i.EscalationLevel,
		&i.RepoName,
		&i.BaseBranch,
		&i.Branch,
		&i.State,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextStage,
		&i.RecoveryStage,
		&i.FeatureID,
		&i.IntakeKey,
		&i.Mode,
		&i.SpecApproval,
		&i.MergeApproval,
		&i.PolicyVersion,
		&i.SetupName,
		&i.SetupContract,
		&i.Hold,
		&i.ReviewedHeadSha,
		&i.ApprovedHeadSha,
		&i.ApprovalStale,
		&i.RefreshBaselineSha,
		&i.RefreshHeadSha,
		&i.RefreshReviewScope,
		&i.OriginSpecVersion,
		&i.OriginSubID,
	)
	return i, err
}

const insertWorkspace = `-- name: InsertWorkspace :one
INSERT INTO workspaces (id, name, config_yaml)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
RETURNING id, name, config_yaml, created_at, config_version
`

type InsertWorkspaceParams struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	ConfigYaml string `json:"config_yaml"`
}

func (q *Queries) InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, insertWorkspace, arg.ID, arg.Name, arg.ConfigYaml)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ConfigYaml,
		&i.CreatedAt,
		&i.ConfigVersion,
	)
	return i, err
}

const insertWorkspaceEvent = `-- name: InsertWorkspaceEvent :one
INSERT INTO events (workspace_id, task_id, job_id, kind, actor_id, actor_role, payload_json, at)
VALUES ($1, NULL, NULL, $2, $3, $4, $5, $6)
RETURNING id, task_id, job_id, kind, actor_id, actor_role, payload_json, at, workspace_id
`

type InsertWorkspaceEventParams struct {
	WorkspaceID string             `json:"workspace_id"`
	Kind        string             `json:"kind"`
	ActorID     string             `json:"actor_id"`
	ActorRole   string             `json:"actor_role"`
	PayloadJson []byte             `json:"payload_json"`
	At          pgtype.Timestamptz `json:"at"`
}

func (q *Queries) InsertWorkspaceEvent(ctx context.Context, arg InsertWorkspaceEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertWorkspaceEvent,
		arg.WorkspaceID,
		arg.Kind,
		arg.ActorID,
		arg.ActorRole,
		arg.PayloadJson,
		arg.At,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.JobID,
		&i.Kind,
		&i.ActorID,
		&i.ActorRole,
		&i.PayloadJson,
		&i.At,
		&i.WorkspaceID,
	)
	return i, err
}

const listActivityMarkers = `-- name: ListActivityMarkers :many
SELECT
    t.id AS task_id,
    COALESCE((
        SELECT j.stage FROM jobs j
        WHERE j.task_id = t.id
        ORDER BY j.started_at DESC, j.id DESC
        LIMIT 1
    ), '')::text AS latest_stage,
    COALESCE((
        SELECT e.at FROM events e
        WHERE e.task_id = t.id
        ORDER BY e.id DESC
        LIMIT 1
    ), t.created_at)::timestamptz AS last_event_at
FROM tasks t
WHERE t.workspace_id = $1
ORDER BY t.created_at, t.id
`

type ListActivityMarkersRow struct {
	TaskID      string             `json:"task_id"`
	LatestStage string             `json:"latest_stage"`
	LastEventAt pgtype.Timestamptz `json:"last_event_at"`
}

func (q *Queries) ListActivityMarkers(ctx context.Context, workspaceID string) ([]ListActivityMarkersRow, error) {
	rows, err := q.db.Query(ctx, listActivityMarkers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityMarkersRow{}
	for rows.Next() {
		var i ListActivityMarkersRow
		if err := rows.Scan(&i.TaskID, &i.LatestStage, &i.LastEventAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT e.id, e.task_id, e.job_id, e.kind, e.actor_id, e.actor_role, e.payload_json, e.at, e.workspace_id FROM events e
JOIN tasks t ON t.id = e.task_id
WHERE e.task_id = $1 AND t.workspace_id = $2
ORDER BY e.at, e.id
`

type ListEventsParams struct {
	TaskID      pgtype.Text `json:"task_id"`
	WorkspaceID string      `json:"workspace_id"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.TaskID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.JobID,
			&i.Kind,
			&i.ActorID,
			&i.ActorRole,
			&i.PayloadJson,
			&i.At,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequirementEvents = `-- name: ListRequirementEvents :many
SELECT e.id, e.task_id, e.job_id, e.kind, e.actor_id, e.actor_role, e.payload_json, e.at, e.workspace_id FROM events e
WHERE e.workspace_id = $1
  AND e.task_id IS NULL
  AND e.payload_json->>'requirement_id' = $2
ORDER BY e.at, e.id
`

type ListRequirementEventsParams struct {
	WorkspaceID   string `json:"workspace_id"`
	RequirementID string `json:"requirement_id"`
}

func (q *Queries) ListRequirementEvents(ctx context.Context, arg ListRequirementEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listRequirementEvents, arg.WorkspaceID, arg.RequirementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.JobID,
			&i.Kind,
			&i.ActorID,
			&i.ActorRole,
			&i.PayloadJson,
			&i.At,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT e.id, e.task_id, e.job_id, e.kind, e.actor_id, e.actor_role, e.payload_json, e.at, e.workspace_id FROM events e
JOIN tasks t ON t.id = e.task_id
WHERE e.task_id = $1 AND t.workspace_id = $2 AND e.id > $3
ORDER BY e.id
`

type ListEventsAfterParams struct {
	TaskID      pgtype.Text `json:"task_id"`
	WorkspaceID string      `json:"workspace_id"`
	ID          int64       `json:"id"`
}

func (q *Queries) ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsAfter, arg.TaskID, arg.WorkspaceID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.JobID,
			&i.Kind,
			&i.ActorID,
			&i.ActorRole,
			&i.PayloadJson,
			&i.At,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInterventions = `-- name: ListInterventions :many
SELECT i.id, i.task_id, i.job_id, i.actor_id, i.actor_role, i.action, i.reason_code, i.comment, i.at FROM interventions i
JOIN tasks t ON t.id = i.task_id
WHERE i.task_id = $1 AND t.workspace_id = $2
ORDER BY i.at, i.id
`

type ListInterventionsParams struct {
	TaskID      string `json:"task_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) ListInterventions(ctx context.Context, arg ListInterventionsParams) ([]Intervention, error) {
	rows, err := q.db.Query(ctx, listInterventions, arg.TaskID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Intervention{}
	for rows.Next() {
		var i Intervention
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.JobID,
			&i.ActorID,
			&i.ActorRole,
			&i.Action,
			&i.ReasonCode,
			&i.Comment,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT j.id, j.task_id, j.stage, j.harness, j.model_tier, j.runner, j.pack_version, j.confinement_tier, j.cost_usd, j.tokens_in, j.tokens_out, j.state, j.started_at, j.ended_at, j.updated_at, j.auth_mode FROM jobs j
JOIN tasks t ON t.id = j.task_id
LEFT JOIN work_orders wo ON wo.job_id = j.id
WHERE j.task_id = $1 AND t.workspace_id = $2
ORDER BY COALESCE(j.started_at, wo.queue_entered_at), j.id
`

type ListJobsParams struct {
	TaskID      string `json:"task_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.TaskID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Stage,
			&i.Harness,
			&i.ModelTier,
			&i.Runner,
			&i.PackVersion,
			&i.ConfinementTier,
			&i.CostUsd,
			&i.TokensIn,
			&i.TokensOut,
			&i.State,
			&i.StartedAt,
			&i.EndedAt,
			&i.UpdatedAt,
			&i.AuthMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT t.id, t.workspace_id, t.source, t.title, t.body, t.class, t.escalation_level, t.repo_name, t.base_branch, t.branch, t.state, t.parent_task_id, t.created_at, t.updated_at, t.next_stage, t.recovery_stage, t.feature_id, t.intake_key, t.mode, t.spec_approval, t.merge_approval, t.policy_version, t.setup_name, t.setup_contract, t.hold, t.reviewed_head_sha, t.approved_head_sha, t.approval_stale, t.refresh_baseline_sha, t.refresh_head_sha, t.refresh_review_scope, t.origin_spec_version, t.origin_sub_id,
       EXISTS (
           SELECT 1 FROM task_dependencies edge
           WHERE edge.workspace_id = t.workspace_id AND edge.task_id = t.id
       ) AS has_dependencies,
       EXISTS (
           SELECT 1 FROM tasks child
           WHERE child.workspace_id = t.workspace_id AND child.parent_task_id = t.id
       ) AS has_children
FROM tasks t
WHERE t.workspace_id = $1
ORDER BY t.created_at, t.id
`

type ListTasksRow struct {
	Task            Task `json:"task"`
	HasDependencies bool `json:"has_dependencies"`
	HasChildren     bool `json:"has_children"`
}

func (q *Queries) ListTasks(ctx context.Context, workspaceID string) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksRow{}
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.Task.ID,
			&i.Task.WorkspaceID,
			&i.Task.Source,
			&i.Task.Title,
			&i.Task.Body,
			&i.Task.Class,
			&i.Task.EscalationLevel,
			&i.Task.RepoName,
			&i.Task.BaseBranch,
			&i.Task.Branch,
			&i.Task.State,
			&i.Task.ParentTaskID,
			&i.Task.CreatedAt,
			&i.Task.UpdatedAt,
			&i.Task.NextStage,
			&i.Task.RecoveryStage,
			&i.Task.FeatureID,
			&i.Task.IntakeKey,
			&i.Task.Mode,
			&i.Task.SpecApproval,
			&i.Task.MergeApproval,
			&i.Task.PolicyVersion,
			&i.Task.SetupName,
			&i.Task.SetupContract,
			&i.Task.Hold,
			&i.Task.ReviewedHeadSha,
			&i.Task.ApprovedHeadSha,
			&i.Task.ApprovalStale,
			&i.Task.RefreshBaselineSha,
			&i.Task.RefreshHeadSha,
			&i.Task.RefreshReviewScope,
			&i.Task.OriginSpecVersion,
			&i.Task.OriginSubID,
			&i.HasDependencies,
			&i.HasChildren,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskApprovalStale = `-- name: MarkTaskApprovalStale :one
UPDATE tasks
SET approved_head_sha = $1, approval_stale = true,
    refresh_baseline_sha = $1,
    refresh_head_sha = $2,
    refresh_review_scope = $3, updated_at = now()
WHERE id = $4 AND workspace_id = $5
  AND NOT (approval_stale
    AND refresh_baseline_sha = $1
    AND refresh_head_sha = $2)
RETURNING id, workspace_id, source, title, body, class, escalation_level, repo_name, base_branch, branch, state, parent_task_id, created_at, updated_at, next_stage, recovery_stage, feature_id, intake_key, mode, spec_approval, merge_approval, policy_version, setup_name, setup_contract, hold, reviewed_head_sha, approved_head_sha, approval_stale, refresh_baseline_sha, refresh_head_sha, refresh_review_scope, origin_spec_version, origin_sub_id
`

type MarkTaskApprovalStaleParams struct {
	ApprovedHeadSha    string `json:"approved_head_sha"`
	NewHeadSha         string `json:"new_head_sha"`
	RefreshReviewScope string `json:"refresh_review_scope"`
	ID                 string `json:"id"`
	WorkspaceID        string `json:"workspace_id"`
}

func (q *Queries) MarkTaskApprovalStale(ctx context.Context, arg MarkTaskApprovalStaleParams) (Task, error) {
	row := q.db.QueryRow(ctx, markTaskApprovalStale,
		arg.ApprovedHeadSha,
		arg.NewHeadSha,
		arg.RefreshReviewScope,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Source,
		&i.Title,
		&i.Body,
		&i.Class,
		&i.EscalationLevel,
		&i.RepoName,
		&i.BaseBranch,
		&i.Branch,
		&i.State,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextStage,
		&i.RecoveryStage,
		&i.FeatureID,
		&i.IntakeKey,
		&i.Mode,
		&i.SpecApproval,
		&i.MergeApproval,
		&i.PolicyVersion,
		&i.SetupName,
		&i.SetupContract,
		&i.Hold,
		&i.ReviewedHeadSha,
		&i.ApprovedHeadSha,
		&i.ApprovalStale,
		&i.RefreshBaselineSha,
		&i.RefreshHeadSha,
		&i.RefreshReviewScope,
		&i.OriginSpecVersion,
		&i.OriginSubID,
	)
	return i, err
}

const skipTaskRefresh = `-- name: SkipTaskRefresh :one
UPDATE tasks
SET reviewed_head_sha = $1, approved_head_sha = $1,
    approval_stale = false, refresh_baseline_sha = '', refresh_head_sha = '',
    refresh_review_scope = '', updated_at = now()
WHERE id = $2 AND workspace_id = $3
RETURNING id, workspace_id, source, title, body, class, escalation_level, repo_name, base_branch, branch, state, parent_task_id, created_at, updated_at, next_stage, recovery_stage, feature_id, intake_key, mode, spec_approval, merge_approval, policy_version, setup_name, setup_contract, hold, reviewed_head_sha, approved_head_sha, approval_stale, refresh_baseline_sha, refresh_head_sha, refresh_review_scope, origin_spec_version, origin_sub_id
`

type SkipTaskRefreshParams struct {
	HeadSha     string `json:"head_sha"`
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) SkipTaskRefresh(ctx context.Context, arg SkipTaskRefreshParams) (Task, error) {
	row := q.db.QueryRow(ctx, skipTaskRefresh, arg.HeadSha, arg.ID, arg.WorkspaceID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Source,
		&i.Title,
		&i.Body,
		&i.Class,
		&i.EscalationLevel,
		&i.RepoName,
		&i.BaseBranch,
		&i.Branch,
		&i.State,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextStage,
		&i.RecoveryStage,
		&i.FeatureID,
		&i.IntakeKey,
		&i.Mode,
		&i.SpecApproval,
		&i.MergeApproval,
		&i.PolicyVersion,
		&i.SetupName,
		&i.SetupContract,
		&i.Hold,
		&i.ReviewedHeadSha,
		&i.ApprovedHeadSha,
		&i.ApprovalStale,
		&i.RefreshBaselineSha,
		&i.RefreshHeadSha,
		&i.RefreshReviewScope,
		&i.OriginSpecVersion,
		&i.OriginSubID,
	)
	return i, err
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET stage = $2,
    harness = $3,
    model_tier = $4,
    auth_mode = $5,
    runner = $6,
    pack_version = $7,
    confinement_tier = $8,
    cost_usd = $9,
    tokens_in = $10,
    tokens_out = $11,
    state = $12,
    started_at = $13,
    ended_at = $14,
    updated_at = now()
WHERE jobs.id = $1
  AND EXISTS (
      SELECT 1 FROM tasks t
      WHERE t.id = jobs.task_id AND t.workspace_id = $15
  )
RETURNING jobs.id, jobs.task_id, jobs.stage, jobs.harness, jobs.model_tier, jobs.runner, jobs.pack_version, jobs.confinement_tier, jobs.cost_usd, jobs.tokens_in, jobs.tokens_out, jobs.state, jobs.started_at, jobs.ended_at, jobs.updated_at, jobs.auth_mode
`

type UpdateJobParams struct {
	ID              string             `json:"id"`
	Stage           string             `json:"stage"`
	Harness         string             `json:"harness"`
	ModelTier       string             `json:"model_tier"`
	AuthMode        string             `json:"auth_mode"`
	Runner          string             `json:"runner"`
	PackVersion     string             `json:"pack_version"`
	ConfinementTier string             `json:"confinement_tier"`
	CostUsd         pgtype.Float8      `json:"cost_usd"`
	TokensIn        int64              `json:"tokens_in"`
	TokensOut       int64              `json:"tokens_out"`
	State           string             `json:"state"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	WorkspaceID     string             `json:"workspace_id"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.ID,
		arg.Stage,
		arg.Harness,
		arg.ModelTier,
		arg.AuthMode,
		arg.Runner,
		arg.PackVersion,
		arg.ConfinementTier,
		arg.CostUsd,
		arg.TokensIn,
		arg.TokensOut,
		arg.State,
		arg.StartedAt,
		arg.EndedAt,
		arg.WorkspaceID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Stage,
		&i.Harness,
		&i.ModelTier,
		&i.Runner,
		&i.PackVersion,
		&i.ConfinementTier,
		&i.CostUsd,
		&i.TokensIn,
		&i.TokensOut,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.UpdatedAt,
		&i.AuthMode,
	)
	return i, err
}

const updateTaskClassification = `-- name: UpdateTaskClassification :one
UPDATE tasks
SET class = $1, updated_at = now()
WHERE id = $2
  AND workspace_id = $3
RETURNING id, workspace_id, source, title, body, class, escalation_level, repo_name, base_branch, branch, state, parent_task_id, created_at, updated_at, next_stage, recovery_stage, feature_id, intake_key, mode, spec_approval, merge_approval, policy_version, setup_name, setup_contract, hold, reviewed_head_sha, approved_head_sha, approval_stale, refresh_baseline_sha, refresh_head_sha, refresh_review_scope, origin_spec_version, origin_sub_id
`

type UpdateTaskClassificationParams struct {
	Class       string `json:"class"`
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) UpdateTaskClassification(ctx context.Context, arg UpdateTaskClassificationParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskClassification, arg.Class, arg.ID, arg.WorkspaceID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Source,
		&i.Title,
		&i.Body,
		&i.Class,
		&i.EscalationLevel,
		&i.RepoName,
		&i.BaseBranch,
		&i.Branch,
		&i.State,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextStage,
		&i.RecoveryStage,
		&i.FeatureID,
		&i.IntakeKey,
		&i.Mode,
		&i.SpecApproval,
		&i.MergeApproval,
		&i.PolicyVersion,
		&i.SetupName,
		&i.SetupContract,
		&i.Hold,
		&i.ReviewedHeadSha,
		&i.ApprovedHeadSha,
		&i.ApprovalStale,
		&i.RefreshBaselineSha,
		&i.RefreshHeadSha,
		&i.RefreshReviewScope,
		&i.OriginSpecVersion,
		&i.OriginSubID,
	)
	return i, err
}

const updateTaskHold = `-- name: UpdateTaskHold :one
UPDATE tasks
SET hold = $1, updated_at = now()
WHERE id = $2
  AND workspace_id = $3
RETURNING id, workspace_id, source, title, body, class, escalation_level, repo_name, base_branch, branch, state, parent_task_id, created_at, updated_at, next_stage, recovery_stage, feature_id, intake_key, mode, spec_approval, merge_approval, policy_version, setup_name, setup_contract, hold, reviewed_head_sha, approved_head_sha, approval_stale, refresh_baseline_sha, refresh_head_sha, refresh_review_scope, origin_spec_version, origin_sub_id
`

type UpdateTaskHoldParams struct {
	Hold        bool   `json:"hold"`
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) UpdateTaskHold(ctx context.Context, arg UpdateTaskHoldParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskHold, arg.Hold, arg.ID, arg.WorkspaceID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Source,
		&i.Title,
		&i.Body,
		&i.Class,
		&i.EscalationLevel,
		&i.RepoName,
		&i.BaseBranch,
		&i.Branch,
		&i.State,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextStage,
		&i.RecoveryStage,
		&i.FeatureID,
		&i.IntakeKey,
		&i.Mode,
		&i.SpecApproval,
		&i.MergeApproval,
		&i.PolicyVersion,
		&i.SetupName,
		&i.SetupContract,
		&i.Hold,
		&i.ReviewedHeadSha,
		&i.ApprovedHeadSha,
		&i.ApprovalStale,
		&i.RefreshBaselineSha,
		&i.RefreshHeadSha,
		&i.RefreshReviewScope,
		&i.OriginSpecVersion,
		&i.OriginSubID,
	)
	return i, err
}

const updateTaskState = `-- name: UpdateTaskState :one
UPDATE tasks
SET state = $1, updated_at = now()
WHERE id = $2
  AND workspace_id = $3
RETURNING id, workspace_id, source, title, body, class, escalation_level, repo_name, base_branch, branch, state, parent_task_id, created_at, updated_at, next_stage, recovery_stage, feature_id, intake_key, mode, spec_approval, merge_approval, policy_version, setup_name, setup_contract, hold, reviewed_head_sha, approved_head_sha, approval_stale, refresh_baseline_sha, refresh_head_sha, refresh_review_scope, origin_spec_version, origin_sub_id
`

type UpdateTaskStateParams struct {
	State       string `json:"state"`
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskState, arg.State, arg.ID, arg.WorkspaceID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Source,
		&i.Title,
		&i.Body,
		&i.Class,
		&i.EscalationLevel,
		&i.RepoName,
		&i.BaseBranch,
		&i.Branch,
		&i.State,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextStage,
		&i.RecoveryStage,
		&i.FeatureID,
		&i.IntakeKey,
		&i.Mode,
		&i.SpecApproval,
		&i.MergeApproval,
		&i.PolicyVersion,
		&i.SetupName,
		&i.SetupContract,
		&i.Hold,
		&i.ReviewedHeadSha,
		&i.ApprovedHeadSha,
		&i.ApprovalStale,
		&i.RefreshBaselineSha,
		&i.RefreshHeadSha,
		&i.RefreshReviewScope,
		&i.OriginSpecVersion,
		&i.OriginSubID,
	)
	return i, err
}

const updateTaskTransition = `-- name: UpdateTaskTransition :one
UPDATE tasks
SET state = $1,
    next_stage = $2,
    recovery_stage = $3,
    updated_at = now()
WHERE id = $4
  AND workspace_id = $5
RETURNING id, workspace_id, source, title, body, class, escalation_level, repo_name, base_branch, branch, state, parent_task_id, created_at, updated_at, next_stage, recovery_stage, feature_id, intake_key, mode, spec_approval, merge_approval, policy_version, setup_name, setup_contract, hold, reviewed_head_sha, approved_head_sha, approval_stale, refresh_baseline_sha, refresh_head_sha, refresh_review_scope, origin_spec_version, origin_sub_id
`

type UpdateTaskTransitionParams struct {
	State         string `json:"state"`
	NextStage     string `json:"next_stage"`
	RecoveryStage string `json:"recovery_stage"`
	ID            string `json:"id"`
	WorkspaceID   string `json:"workspace_id"`
}

func (q *Queries) UpdateTaskTransition(ctx context.Context, arg UpdateTaskTransitionParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskTransition,
		arg.State,
		arg.NextStage,
		arg.RecoveryStage,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Source,
		&i.Title,
		&i.Body,
		&i.Class,
		&i.EscalationLevel,
		&i.RepoName,
		&i.BaseBranch,
		&i.Branch,
		&i.State,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextStage,
		&i.RecoveryStage,
		&i.FeatureID,
		&i.IntakeKey,
		&i.Mode,
		&i.SpecApproval,
		&i.MergeApproval,
		&i.PolicyVersion,
		&i.SetupName,
		&i.SetupContract,
		&i.Hold,
		&i.ReviewedHeadSha,
		&i.ApprovedHeadSha,
		&i.ApprovalStale,
		&i.RefreshBaselineSha,
		&i.RefreshHeadSha,
		&i.RefreshReviewScope,
		&i.OriginSpecVersion,
		&i.OriginSubID,
	)
	return i, err
}

const updateWorkspaceConfig = `-- name: UpdateWorkspaceConfig :one
UPDATE workspaces
SET config_yaml = $1,
    config_version = config_version + 1
WHERE id = $2
  AND config_version = $3
RETURNING id, name, config_yaml, created_at, config_version
`

type UpdateWorkspaceConfigParams struct {
	ConfigYaml      string `json:"config_yaml"`
	ID              string `json:"id"`
	ExpectedVersion int64  `json:"expected_version"`
}

func (q *Queries) UpdateWorkspaceConfig(ctx context.Context, arg UpdateWorkspaceConfigParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceConfig, arg.ConfigYaml, arg.ID, arg.ExpectedVersion)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ConfigYaml,
		&i.CreatedAt,
		&i.ConfigVersion,
	)
	return i, err
}

const upsertRepo = `-- name: UpsertRepo :exec
INSERT INTO repos (workspace_id, name, url, github_slug, default_base, devcontainer_path)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (workspace_id, name) DO UPDATE
SET url = EXCLUDED.url,
    github_slug = EXCLUDED.github_slug,
    default_base = EXCLUDED.default_base,
    devcontainer_path = EXCLUDED.devcontainer_path
`

type UpsertRepoParams struct {
	WorkspaceID      string `json:"workspace_id"`
	Name             string `json:"name"`
	Url              string `json:"url"`
	GithubSlug       string `json:"github_slug"`
	DefaultBase      string `json:"default_base"`
	DevcontainerPath string `json:"devcontainer_path"`
}

func (q *Queries) UpsertRepo(ctx context.Context, arg UpsertRepoParams) error {
	_, err := q.db.Exec(ctx, upsertRepo,
		arg.WorkspaceID,
		arg.Name,
		arg.Url,
		arg.GithubSlug,
		arg.DefaultBase,
		arg.DevcontainerPath,
	)
	return err
}

const upsertTranscript = `-- name: UpsertTranscript :one
INSERT INTO transcripts (job_id, uri, redaction_stats, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (job_id) DO UPDATE
SET uri = EXCLUDED.uri,
    redaction_stats = EXCLUDED.redaction_stats
RETURNING job_id, uri, redaction_stats, created_at
`

type UpsertTranscriptParams struct {
	JobID          string             `json:"job_id"`
	Uri            string             `json:"uri"`
	RedactionStats []byte             `json:"redaction_stats"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertTranscript(ctx context.Context, arg UpsertTranscriptParams) (Transcript, error) {
	row := q.db.QueryRow(ctx, upsertTranscript,
		arg.JobID,
		arg.Uri,
		arg.RedactionStats,
		arg.CreatedAt,
	)
	var i Transcript
	err := row.Scan(
		&i.JobID,
		&i.Uri,
		&i.RedactionStats,
		&i.CreatedAt,
	)
	return i, err
}
