// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: control_plane.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveLatestSpecVersion = `-- name: ApproveLatestSpecVersion :one
UPDATE task_specs s
SET approved = true, approved_at = now()
FROM tasks t
WHERE s.task_id = t.id
  AND s.task_id = $1
  AND s.version = $2
  AND t.workspace_id = $3
  AND s.version = (SELECT MAX(version) FROM task_specs WHERE task_id = $1)
RETURNING s.task_id, s.version, s.content, s.acceptance_count, s.acceptance, s.decomposition, s.approved, s.created_at, s.approved_at
`

type ApproveLatestSpecVersionParams struct {
	TaskID      string `json:"task_id"`
	Version     int32  `json:"version"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) ApproveLatestSpecVersion(ctx context.Context, arg ApproveLatestSpecVersionParams) (TaskSpec, error) {
	row := q.db.QueryRow(ctx, approveLatestSpecVersion, arg.TaskID, arg.Version, arg.WorkspaceID)
	var i TaskSpec
	err := row.Scan(
		&i.TaskID,
		&i.Version,
		&i.Content,
		&i.AcceptanceCount,
		&i.Acceptance,
		&i.Decomposition,
		&i.Approved,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}

const claimCredential = `-- name: ClaimCredential :one
WITH candidate AS (
    SELECT c.id
    FROM credentials c
    LEFT JOIN vendor_policies p
      ON p.vendor = c.vendor AND p.harness = c.harness AND p.auth_mode = c.kind
    WHERE c.harness = ANY($4::text[])
      AND ($5::text = '' OR c.harness <> $5::text)
      AND (c.owner_kind = 'org' OR c.owner_id = $6)
      AND (c.kind = 'api' OR c.owner_kind = 'user')
      AND (c.leased_by = $1 OR c.lease_until IS NULL OR c.lease_until <= now())
      AND (c.cooldown_until IS NULL OR c.cooldown_until <= now())
      AND c.rate_limit_state <> 'disabled'
      AND (
          c.kind = 'api'
          OR p.subscription_headless = 'allowed'
          OR ($7::boolean AND p.subscription_headless = 'restricted')
      )
    ORDER BY array_position($4::text[], c.harness),
             CASE c.kind WHEN 'personal_sub' THEN 0 WHEN 'team_sub' THEN 1 ELSE 2 END,
             c.updated_at,
             c.id
    FOR UPDATE OF c SKIP LOCKED
    LIMIT 1
)
UPDATE credentials c
SET leased_by = $1,
    lease_task_id = $2,
    lease_until = now() + $3::bigint * interval '1 second',
    rate_limit_state = 'available',
    cooldown_until = NULL,
    last_error = '',
    updated_at = now()
FROM candidate
WHERE c.id = candidate.id
RETURNING c.id, c.owner_id, c.owner_kind, c.kind, c.harness, c.enc_ref, c.rate_limit_state, c.policy_flag, c.cooldown_until, c.last_error, c.created_at, c.updated_at, c.vendor, c.leased_by, c.lease_until, c.lease_task_id
`

type ClaimCredentialParams struct {
	JobID           string   `json:"job_id"`
	TaskID          string   `json:"task_id"`
	LeaseSeconds    int64    `json:"lease_seconds"`
	Harnesses       []string `json:"harnesses"`
	ExcludeHarness  string   `json:"exclude_harness"`
	OwnerID         string   `json:"owner_id"`
	AllowRestricted bool     `json:"allow_restricted"`
}

func (q *Queries) ClaimCredential(ctx context.Context, arg ClaimCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, claimCredential,
		arg.JobID,
		arg.TaskID,
		arg.LeaseSeconds,
		arg.Harnesses,
		arg.ExcludeHarness,
		arg.OwnerID,
		arg.AllowRestricted,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.OwnerKind,
		&i.Kind,
		&i.Harness,
		&i.EncRef,
		&i.RateLimitState,
		&i.PolicyFlag,
		&i.CooldownUntil,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Vendor,
		&i.LeasedBy,
		&i.LeaseUntil,
		&i.LeaseTaskID,
	)
	return i, err
}

const countEvents = `-- name: CountEvents :one
SELECT count(*)::bigint FROM events e
JOIN tasks t ON t.id = e.task_id
WHERE e.task_id = $1 AND e.kind = $2 AND t.workspace_id = $3
`

type CountEventsParams struct {
	TaskID      string `json:"task_id"`
	Kind        string `json:"kind"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) CountEvents(ctx context.Context, arg CountEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEvents, arg.TaskID, arg.Kind, arg.WorkspaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteWorkspaceCredentialRefs = `-- name: DeleteWorkspaceCredentialRefs :exec
DELETE FROM workspace_credentials WHERE workspace_id = $1
`

func (q *Queries) DeleteWorkspaceCredentialRefs(ctx context.Context, workspaceID string) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceCredentialRefs, workspaceID)
	return err
}

const deleteWorkspaceVendorPolicyRefs = `-- name: DeleteWorkspaceVendorPolicyRefs :exec
DELETE FROM workspace_vendor_policies WHERE workspace_id = $1
`

func (q *Queries) DeleteWorkspaceVendorPolicyRefs(ctx context.Context, workspaceID string) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceVendorPolicyRefs, workspaceID)
	return err
}

const disableCredentialIfUnreferenced = `-- name: DisableCredentialIfUnreferenced :exec
UPDATE credentials c
SET rate_limit_state = 'disabled', updated_at = now()
WHERE c.id = $1
  AND c.rate_limit_state <> 'disabled'
  AND NOT EXISTS (
      SELECT 1 FROM workspace_credentials wc WHERE wc.credential_id = c.id
  )
`

func (q *Queries) DisableCredentialIfUnreferenced(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, disableCredentialIfUnreferenced, id)
	return err
}

const enableCredential = `-- name: EnableCredential :exec
UPDATE credentials
SET rate_limit_state = 'available', updated_at = now()
WHERE id = $1 AND rate_limit_state = 'disabled'
`

func (q *Queries) EnableCredential(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, enableCredential, id)
	return err
}

const getJob = `-- name: GetJob :one
SELECT j.id, j.task_id, j.stage, j.harness, j.model_tier, j.runner, j.sandbox_ref, j.pack_version, j.confinement_tier, j.budget_usd, j.cost_usd, j.tokens_in, j.tokens_out, j.state, j.boot_diagnostics, j.started_at, j.ended_at, j.updated_at, j.credential_id, j.auth_mode FROM jobs j
JOIN tasks t ON t.id = j.task_id
WHERE j.id = $1 AND t.workspace_id = $2
`

type GetJobParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, arg.ID, arg.WorkspaceID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Stage,
		&i.Harness,
		&i.ModelTier,
		&i.Runner,
		&i.SandboxRef,
		&i.PackVersion,
		&i.ConfinementTier,
		&i.BudgetUsd,
		&i.CostUsd,
		&i.TokensIn,
		&i.TokensOut,
		&i.State,
		&i.BootDiagnostics,
		&i.StartedAt,
		&i.EndedAt,
		&i.UpdatedAt,
		&i.CredentialID,
		&i.AuthMode,
	)
	return i, err
}

const getLatestJob = `-- name: GetLatestJob :one
SELECT j.id, j.task_id, j.stage, j.harness, j.model_tier, j.runner, j.sandbox_ref, j.pack_version, j.confinement_tier, j.budget_usd, j.cost_usd, j.tokens_in, j.tokens_out, j.state, j.boot_diagnostics, j.started_at, j.ended_at, j.updated_at, j.credential_id, j.auth_mode FROM jobs j
JOIN tasks t ON t.id = j.task_id
WHERE j.task_id = $1 AND t.workspace_id = $2
ORDER BY j.started_at DESC, j.id DESC
LIMIT 1
`

type GetLatestJobParams struct {
	TaskID      string `json:"task_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetLatestJob(ctx context.Context, arg GetLatestJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, getLatestJob, arg.TaskID, arg.WorkspaceID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Stage,
		&i.Harness,
		&i.ModelTier,
		&i.Runner,
		&i.SandboxRef,
		&i.PackVersion,
		&i.ConfinementTier,
		&i.BudgetUsd,
		&i.CostUsd,
		&i.TokensIn,
		&i.TokensOut,
		&i.State,
		&i.BootDiagnostics,
		&i.StartedAt,
		&i.EndedAt,
		&i.UpdatedAt,
		&i.CredentialID,
		&i.AuthMode,
	)
	return i, err
}

const getLatestSpecVersion = `-- name: GetLatestSpecVersion :one
SELECT s.task_id, s.version, s.content, s.acceptance_count, s.acceptance, s.decomposition, s.approved, s.created_at, s.approved_at FROM task_specs s
JOIN tasks t ON t.id = s.task_id
WHERE s.task_id = $1 AND t.workspace_id = $2
ORDER BY s.version DESC
LIMIT 1
`

type GetLatestSpecVersionParams struct {
	TaskID      string `json:"task_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetLatestSpecVersion(ctx context.Context, arg GetLatestSpecVersionParams) (TaskSpec, error) {
	row := q.db.QueryRow(ctx, getLatestSpecVersion, arg.TaskID, arg.WorkspaceID)
	var i TaskSpec
	err := row.Scan(
		&i.TaskID,
		&i.Version,
		&i.Content,
		&i.AcceptanceCount,
		&i.Acceptance,
		&i.Decomposition,
		&i.Approved,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, workspace_id, source, title, body, class, escalation_level, repo_name, base_branch, branch, state, parent_task_id, created_at, updated_at, next_stage, recovery_stage FROM tasks WHERE id = $1 AND workspace_id = $2
`

type GetTaskParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.WorkspaceID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Source,
		&i.Title,
		&i.Body,
		&i.Class,
		&i.EscalationLevel,
		&i.RepoName,
		&i.BaseBranch,
		&i.Branch,
		&i.State,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextStage,
		&i.RecoveryStage,
	)
	return i, err
}

const getTranscript = `-- name: GetTranscript :one
SELECT tr.job_id, tr.uri, tr.redaction_stats, tr.created_at FROM transcripts tr
JOIN jobs j ON j.id = tr.job_id
JOIN tasks t ON t.id = j.task_id
WHERE tr.job_id = $1 AND t.workspace_id = $2
`

type GetTranscriptParams struct {
	JobID       string `json:"job_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetTranscript(ctx context.Context, arg GetTranscriptParams) (Transcript, error) {
	row := q.db.QueryRow(ctx, getTranscript, arg.JobID, arg.WorkspaceID)
	var i Transcript
	err := row.Scan(
		&i.JobID,
		&i.Uri,
		&i.RedactionStats,
		&i.CreatedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (task_id, job_id, kind, actor_id, actor_role, payload_json, at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, task_id, job_id, kind, actor_id, actor_role, payload_json, at
`

type InsertEventParams struct {
	TaskID      string             `json:"task_id"`
	JobID       pgtype.Text        `json:"job_id"`
	Kind        string             `json:"kind"`
	ActorID     string             `json:"actor_id"`
	ActorRole   string             `json:"actor_role"`
	PayloadJson []byte             `json:"payload_json"`
	At          pgtype.Timestamptz `json:"at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.TaskID,
		arg.JobID,
		arg.Kind,
		arg.ActorID,
		arg.ActorRole,
		arg.PayloadJson,
		arg.At,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.JobID,
		&i.Kind,
		&i.ActorID,
		&i.ActorRole,
		&i.PayloadJson,
		&i.At,
	)
	return i, err
}

const insertIntervention = `-- name: InsertIntervention :one
INSERT INTO interventions (
    task_id, job_id, actor_id, actor_role, action, reason_code, comment, at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, task_id, job_id, actor_id, actor_role, action, reason_code, comment, at
`

type InsertInterventionParams struct {
	TaskID     string             `json:"task_id"`
	JobID      pgtype.Text        `json:"job_id"`
	ActorID    string             `json:"actor_id"`
	ActorRole  string             `json:"actor_role"`
	Action     string             `json:"action"`
	ReasonCode string             `json:"reason_code"`
	Comment    string             `json:"comment"`
	At         pgtype.Timestamptz `json:"at"`
}

func (q *Queries) InsertIntervention(ctx context.Context, arg InsertInterventionParams) (Intervention, error) {
	row := q.db.QueryRow(ctx, insertIntervention,
		arg.TaskID,
		arg.JobID,
		arg.ActorID,
		arg.ActorRole,
		arg.Action,
		arg.ReasonCode,
		arg.Comment,
		arg.At,
	)
	var i Intervention
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.JobID,
		&i.ActorID,
		&i.ActorRole,
		&i.Action,
		&i.ReasonCode,
		&i.Comment,
		&i.At,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO jobs (
    id, task_id, stage, harness, model_tier, credential_id, auth_mode, runner, sandbox_ref,
    pack_version, confinement_tier, budget_usd, cost_usd, tokens_in,
    tokens_out, state, boot_diagnostics, started_at, ended_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19
)
RETURNING id, task_id, stage, harness, model_tier, runner, sandbox_ref, pack_version, confinement_tier, budget_usd, cost_usd, tokens_in, tokens_out, state, boot_diagnostics, started_at, ended_at, updated_at, credential_id, auth_mode
`

type InsertJobParams struct {
	ID              string             `json:"id"`
	TaskID          string             `json:"task_id"`
	Stage           string             `json:"stage"`
	Harness         string             `json:"harness"`
	ModelTier       string             `json:"model_tier"`
	CredentialID    string             `json:"credential_id"`
	AuthMode        string             `json:"auth_mode"`
	Runner          string             `json:"runner"`
	SandboxRef      string             `json:"sandbox_ref"`
	PackVersion     string             `json:"pack_version"`
	ConfinementTier string             `json:"confinement_tier"`
	BudgetUsd       float64            `json:"budget_usd"`
	CostUsd         float64            `json:"cost_usd"`
	TokensIn        int64              `json:"tokens_in"`
	TokensOut       int64              `json:"tokens_out"`
	State           string             `json:"state"`
	BootDiagnostics []byte             `json:"boot_diagnostics"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, insertJob,
		arg.ID,
		arg.TaskID,
		arg.Stage,
		arg.Harness,
		arg.ModelTier,
		arg.CredentialID,
		arg.AuthMode,
		arg.Runner,
		arg.SandboxRef,
		arg.PackVersion,
		arg.ConfinementTier,
		arg.BudgetUsd,
		arg.CostUsd,
		arg.TokensIn,
		arg.TokensOut,
		arg.State,
		arg.BootDiagnostics,
		arg.StartedAt,
		arg.EndedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Stage,
		&i.Harness,
		&i.ModelTier,
		&i.Runner,
		&i.SandboxRef,
		&i.PackVersion,
		&i.ConfinementTier,
		&i.BudgetUsd,
		&i.CostUsd,
		&i.TokensIn,
		&i.TokensOut,
		&i.State,
		&i.BootDiagnostics,
		&i.StartedAt,
		&i.EndedAt,
		&i.UpdatedAt,
		&i.CredentialID,
		&i.AuthMode,
	)
	return i, err
}

const insertSpecVersion = `-- name: InsertSpecVersion :one
INSERT INTO task_specs (
    task_id, version, content, acceptance_count, acceptance, decomposition,
    approved, approved_at, created_at
)
SELECT
    $1,
    COALESCE(MAX(version), 0) + 1,
    $2,
    $3,
    $4,
    $5,
    false,
    NULL,
    $6
FROM task_specs
WHERE task_id = $1
RETURNING task_id, version, content, acceptance_count, acceptance, decomposition, approved, created_at, approved_at
`

type InsertSpecVersionParams struct {
	TaskID          string             `json:"task_id"`
	Content         string             `json:"content"`
	AcceptanceCount int32              `json:"acceptance_count"`
	Acceptance      []byte             `json:"acceptance"`
	Decomposition   []byte             `json:"decomposition"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertSpecVersion(ctx context.Context, arg InsertSpecVersionParams) (TaskSpec, error) {
	row := q.db.QueryRow(ctx, insertSpecVersion,
		arg.TaskID,
		arg.Content,
		arg.AcceptanceCount,
		arg.Acceptance,
		arg.Decomposition,
		arg.CreatedAt,
	)
	var i TaskSpec
	err := row.Scan(
		&i.TaskID,
		&i.Version,
		&i.Content,
		&i.AcceptanceCount,
		&i.Acceptance,
		&i.Decomposition,
		&i.Approved,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}

const insertTask = `-- name: InsertTask :one
INSERT INTO tasks (
    id, workspace_id, source, title, body, class, escalation_level,
    repo_name, base_branch, branch, state, next_stage, recovery_stage, parent_task_id, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, workspace_id, source, title, body, class, escalation_level, repo_name, base_branch, branch, state, parent_task_id, created_at, updated_at, next_stage, recovery_stage
`

type InsertTaskParams struct {
	ID              string             `json:"id"`
	WorkspaceID     string             `json:"workspace_id"`
	Source          string             `json:"source"`
	Title           string             `json:"title"`
	Body            string             `json:"body"`
	Class           string             `json:"class"`
	EscalationLevel string             `json:"escalation_level"`
	RepoName        string             `json:"repo_name"`
	BaseBranch      string             `json:"base_branch"`
	Branch          string             `json:"branch"`
	State           string             `json:"state"`
	NextStage       string             `json:"next_stage"`
	RecoveryStage   string             `json:"recovery_stage"`
	ParentTaskID    string             `json:"parent_task_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, insertTask,
		arg.ID,
		arg.WorkspaceID,
		arg.Source,
		arg.Title,
		arg.Body,
		arg.Class,
		arg.EscalationLevel,
		arg.RepoName,
		arg.BaseBranch,
		arg.Branch,
		arg.State,
		arg.NextStage,
		arg.RecoveryStage,
		arg.ParentTaskID,
		arg.CreatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Source,
		&i.Title,
		&i.Body,
		&i.Class,
		&i.EscalationLevel,
		&i.RepoName,
		&i.BaseBranch,
		&i.Branch,
		&i.State,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextStage,
		&i.RecoveryStage,
	)
	return i, err
}

const insertWorkspaceCredentialRef = `-- name: InsertWorkspaceCredentialRef :exec
INSERT INTO workspace_credentials (workspace_id, credential_id)
VALUES ($1, $2)
`

type InsertWorkspaceCredentialRefParams struct {
	WorkspaceID  string `json:"workspace_id"`
	CredentialID string `json:"credential_id"`
}

func (q *Queries) InsertWorkspaceCredentialRef(ctx context.Context, arg InsertWorkspaceCredentialRefParams) error {
	_, err := q.db.Exec(ctx, insertWorkspaceCredentialRef, arg.WorkspaceID, arg.CredentialID)
	return err
}

const insertWorkspaceVendorPolicyRef = `-- name: InsertWorkspaceVendorPolicyRef :exec
INSERT INTO workspace_vendor_policies (workspace_id, vendor, harness, auth_mode)
VALUES ($1, $2, $3, $4)
`

type InsertWorkspaceVendorPolicyRefParams struct {
	WorkspaceID string `json:"workspace_id"`
	Vendor      string `json:"vendor"`
	Harness     string `json:"harness"`
	AuthMode    string `json:"auth_mode"`
}

func (q *Queries) InsertWorkspaceVendorPolicyRef(ctx context.Context, arg InsertWorkspaceVendorPolicyRefParams) error {
	_, err := q.db.Exec(ctx, insertWorkspaceVendorPolicyRef,
		arg.WorkspaceID,
		arg.Vendor,
		arg.Harness,
		arg.AuthMode,
	)
	return err
}

const listActivityMarkers = `-- name: ListActivityMarkers :many
SELECT
    t.id AS task_id,
    COALESCE((
        SELECT j.stage FROM jobs j
        WHERE j.task_id = t.id
        ORDER BY j.started_at DESC, j.id DESC
        LIMIT 1
    ), '')::text AS latest_stage,
    COALESCE((
        SELECT e.at FROM events e
        WHERE e.task_id = t.id
        ORDER BY e.id DESC
        LIMIT 1
    ), t.created_at)::timestamptz AS last_event_at
FROM tasks t
WHERE t.workspace_id = $1
ORDER BY t.created_at, t.id
`

type ListActivityMarkersRow struct {
	TaskID      string             `json:"task_id"`
	LatestStage string             `json:"latest_stage"`
	LastEventAt pgtype.Timestamptz `json:"last_event_at"`
}

func (q *Queries) ListActivityMarkers(ctx context.Context, workspaceID string) ([]ListActivityMarkersRow, error) {
	rows, err := q.db.Query(ctx, listActivityMarkers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityMarkersRow{}
	for rows.Next() {
		var i ListActivityMarkersRow
		if err := rows.Scan(&i.TaskID, &i.LatestStage, &i.LastEventAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentials = `-- name: ListCredentials :many
SELECT id, owner_id, owner_kind, kind, harness, enc_ref, rate_limit_state, policy_flag, cooldown_until, last_error, created_at, updated_at, vendor, leased_by, lease_until, lease_task_id FROM credentials ORDER BY harness, owner_id, id
`

func (q *Queries) ListCredentials(ctx context.Context) ([]Credential, error) {
	rows, err := q.db.Query(ctx, listCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Credential{}
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.OwnerKind,
			&i.Kind,
			&i.Harness,
			&i.EncRef,
			&i.RateLimitState,
			&i.PolicyFlag,
			&i.CooldownUntil,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Vendor,
			&i.LeasedBy,
			&i.LeaseUntil,
			&i.LeaseTaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT e.id, e.task_id, e.job_id, e.kind, e.actor_id, e.actor_role, e.payload_json, e.at FROM events e
JOIN tasks t ON t.id = e.task_id
WHERE e.task_id = $1 AND t.workspace_id = $2
ORDER BY e.at, e.id
`

type ListEventsParams struct {
	TaskID      string `json:"task_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.TaskID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.JobID,
			&i.Kind,
			&i.ActorID,
			&i.ActorRole,
			&i.PayloadJson,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT e.id, e.task_id, e.job_id, e.kind, e.actor_id, e.actor_role, e.payload_json, e.at FROM events e
JOIN tasks t ON t.id = e.task_id
WHERE e.task_id = $1 AND t.workspace_id = $2 AND e.id > $3
ORDER BY e.id
`

type ListEventsAfterParams struct {
	TaskID      string `json:"task_id"`
	WorkspaceID string `json:"workspace_id"`
	ID          int64  `json:"id"`
}

func (q *Queries) ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsAfter, arg.TaskID, arg.WorkspaceID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.JobID,
			&i.Kind,
			&i.ActorID,
			&i.ActorRole,
			&i.PayloadJson,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInterventions = `-- name: ListInterventions :many
SELECT i.id, i.task_id, i.job_id, i.actor_id, i.actor_role, i.action, i.reason_code, i.comment, i.at FROM interventions i
JOIN tasks t ON t.id = i.task_id
WHERE i.task_id = $1 AND t.workspace_id = $2
ORDER BY i.at, i.id
`

type ListInterventionsParams struct {
	TaskID      string `json:"task_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) ListInterventions(ctx context.Context, arg ListInterventionsParams) ([]Intervention, error) {
	rows, err := q.db.Query(ctx, listInterventions, arg.TaskID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Intervention{}
	for rows.Next() {
		var i Intervention
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.JobID,
			&i.ActorID,
			&i.ActorRole,
			&i.Action,
			&i.ReasonCode,
			&i.Comment,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT j.id, j.task_id, j.stage, j.harness, j.model_tier, j.runner, j.sandbox_ref, j.pack_version, j.confinement_tier, j.budget_usd, j.cost_usd, j.tokens_in, j.tokens_out, j.state, j.boot_diagnostics, j.started_at, j.ended_at, j.updated_at, j.credential_id, j.auth_mode FROM jobs j
JOIN tasks t ON t.id = j.task_id
WHERE j.task_id = $1 AND t.workspace_id = $2
ORDER BY j.started_at, j.id
`

type ListJobsParams struct {
	TaskID      string `json:"task_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.TaskID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Stage,
			&i.Harness,
			&i.ModelTier,
			&i.Runner,
			&i.SandboxRef,
			&i.PackVersion,
			&i.ConfinementTier,
			&i.BudgetUsd,
			&i.CostUsd,
			&i.TokensIn,
			&i.TokensOut,
			&i.State,
			&i.BootDiagnostics,
			&i.StartedAt,
			&i.EndedAt,
			&i.UpdatedAt,
			&i.CredentialID,
			&i.AuthMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, workspace_id, source, title, body, class, escalation_level, repo_name, base_branch, branch, state, parent_task_id, created_at, updated_at, next_stage, recovery_stage FROM tasks WHERE workspace_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListTasks(ctx context.Context, workspaceID string) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Source,
			&i.Title,
			&i.Body,
			&i.Class,
			&i.EscalationLevel,
			&i.RepoName,
			&i.BaseBranch,
			&i.Branch,
			&i.State,
			&i.ParentTaskID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextStage,
			&i.RecoveryStage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorPolicies = `-- name: ListVendorPolicies :many
SELECT vendor, harness, auth_mode, subscription_headless, reviewed_at, source_url, updated_at FROM vendor_policies ORDER BY vendor, harness, auth_mode
`

func (q *Queries) ListVendorPolicies(ctx context.Context) ([]VendorPolicy, error) {
	rows, err := q.db.Query(ctx, listVendorPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VendorPolicy{}
	for rows.Next() {
		var i VendorPolicy
		if err := rows.Scan(
			&i.Vendor,
			&i.Harness,
			&i.AuthMode,
			&i.SubscriptionHeadless,
			&i.ReviewedAt,
			&i.SourceUrl,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceCredentialIDs = `-- name: ListWorkspaceCredentialIDs :many
SELECT credential_id
FROM workspace_credentials
WHERE workspace_id = $1
ORDER BY credential_id
`

func (q *Queries) ListWorkspaceCredentialIDs(ctx context.Context, workspaceID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listWorkspaceCredentialIDs, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var credential_id string
		if err := rows.Scan(&credential_id); err != nil {
			return nil, err
		}
		items = append(items, credential_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceVendorPolicyRefs = `-- name: ListWorkspaceVendorPolicyRefs :many
SELECT vendor, harness, auth_mode
FROM workspace_vendor_policies
WHERE workspace_id = $1
ORDER BY vendor, harness, auth_mode
`

type ListWorkspaceVendorPolicyRefsRow struct {
	Vendor   string `json:"vendor"`
	Harness  string `json:"harness"`
	AuthMode string `json:"auth_mode"`
}

func (q *Queries) ListWorkspaceVendorPolicyRefs(ctx context.Context, workspaceID string) ([]ListWorkspaceVendorPolicyRefsRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceVendorPolicyRefs, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceVendorPolicyRefsRow{}
	for rows.Next() {
		var i ListWorkspaceVendorPolicyRefsRow
		if err := rows.Scan(&i.Vendor, &i.Harness, &i.AuthMode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseCredential = `-- name: ReleaseCredential :execrows
UPDATE credentials
SET leased_by = '', lease_task_id = '', lease_until = NULL, last_error = $1, updated_at = now()
WHERE id = $2 AND leased_by = $3
`

type ReleaseCredentialParams struct {
	LastError string `json:"last_error"`
	ID        string `json:"id"`
	JobID     string `json:"job_id"`
}

func (q *Queries) ReleaseCredential(ctx context.Context, arg ReleaseCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseCredential, arg.LastError, arg.ID, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rescueTaskCredentialLeases = `-- name: RescueTaskCredentialLeases :execrows
UPDATE credentials
SET leased_by = '', lease_task_id = '', lease_until = NULL,
    last_error = 'rescued after abandoned task attempt', updated_at = now()
WHERE lease_task_id = $1
  AND leased_by <> ''
  AND leased_by <> $2
`

type RescueTaskCredentialLeasesParams struct {
	TaskID       string `json:"task_id"`
	CurrentJobID string `json:"current_job_id"`
}

func (q *Queries) RescueTaskCredentialLeases(ctx context.Context, arg RescueTaskCredentialLeasesParams) (int64, error) {
	result, err := q.db.Exec(ctx, rescueTaskCredentialLeases, arg.TaskID, arg.CurrentJobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restrictVendorPolicyIfUnreferenced = `-- name: RestrictVendorPolicyIfUnreferenced :exec
UPDATE vendor_policies p
SET subscription_headless = 'unknown', updated_at = now()
WHERE p.vendor = $1 AND p.harness = $2 AND p.auth_mode = $3
  AND p.subscription_headless <> 'unknown'
  AND NOT EXISTS (
      SELECT 1
      FROM workspace_vendor_policies wp
      WHERE wp.vendor = p.vendor
        AND wp.harness = p.harness
        AND wp.auth_mode = p.auth_mode
  )
`

type RestrictVendorPolicyIfUnreferencedParams struct {
	Vendor   string `json:"vendor"`
	Harness  string `json:"harness"`
	AuthMode string `json:"auth_mode"`
}

func (q *Queries) RestrictVendorPolicyIfUnreferenced(ctx context.Context, arg RestrictVendorPolicyIfUnreferencedParams) error {
	_, err := q.db.Exec(ctx, restrictVendorPolicyIfUnreferenced, arg.Vendor, arg.Harness, arg.AuthMode)
	return err
}

const throttleCredential = `-- name: ThrottleCredential :execrows
UPDATE credentials
SET leased_by = '',
    lease_task_id = '',
    lease_until = NULL,
    rate_limit_state = 'throttled',
    cooldown_until = now() + $1::bigint * interval '1 second',
    last_error = $2,
    updated_at = now()
WHERE id = $3 AND leased_by = $4
`

type ThrottleCredentialParams struct {
	CooldownSeconds int64  `json:"cooldown_seconds"`
	LastError       string `json:"last_error"`
	ID              string `json:"id"`
	JobID           string `json:"job_id"`
}

func (q *Queries) ThrottleCredential(ctx context.Context, arg ThrottleCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, throttleCredential,
		arg.CooldownSeconds,
		arg.LastError,
		arg.ID,
		arg.JobID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET stage = $2,
    harness = $3,
    model_tier = $4,
    credential_id = $5,
    auth_mode = $6,
    runner = $7,
    sandbox_ref = $8,
    pack_version = $9,
    confinement_tier = $10,
    budget_usd = $11,
    cost_usd = $12,
    tokens_in = $13,
    tokens_out = $14,
    state = $15,
    boot_diagnostics = $16,
    started_at = $17,
    ended_at = $18,
    updated_at = now()
WHERE jobs.id = $1
  AND EXISTS (
      SELECT 1 FROM tasks t
      WHERE t.id = jobs.task_id AND t.workspace_id = $19
  )
RETURNING jobs.id, jobs.task_id, jobs.stage, jobs.harness, jobs.model_tier, jobs.runner, jobs.sandbox_ref, jobs.pack_version, jobs.confinement_tier, jobs.budget_usd, jobs.cost_usd, jobs.tokens_in, jobs.tokens_out, jobs.state, jobs.boot_diagnostics, jobs.started_at, jobs.ended_at, jobs.updated_at, jobs.credential_id, jobs.auth_mode
`

type UpdateJobParams struct {
	ID              string             `json:"id"`
	Stage           string             `json:"stage"`
	Harness         string             `json:"harness"`
	ModelTier       string             `json:"model_tier"`
	CredentialID    string             `json:"credential_id"`
	AuthMode        string             `json:"auth_mode"`
	Runner          string             `json:"runner"`
	SandboxRef      string             `json:"sandbox_ref"`
	PackVersion     string             `json:"pack_version"`
	ConfinementTier string             `json:"confinement_tier"`
	BudgetUsd       float64            `json:"budget_usd"`
	CostUsd         float64            `json:"cost_usd"`
	TokensIn        int64              `json:"tokens_in"`
	TokensOut       int64              `json:"tokens_out"`
	State           string             `json:"state"`
	BootDiagnostics []byte             `json:"boot_diagnostics"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	WorkspaceID     string             `json:"workspace_id"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.ID,
		arg.Stage,
		arg.Harness,
		arg.ModelTier,
		arg.CredentialID,
		arg.AuthMode,
		arg.Runner,
		arg.SandboxRef,
		arg.PackVersion,
		arg.ConfinementTier,
		arg.BudgetUsd,
		arg.CostUsd,
		arg.TokensIn,
		arg.TokensOut,
		arg.State,
		arg.BootDiagnostics,
		arg.StartedAt,
		arg.EndedAt,
		arg.WorkspaceID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Stage,
		&i.Harness,
		&i.ModelTier,
		&i.Runner,
		&i.SandboxRef,
		&i.PackVersion,
		&i.ConfinementTier,
		&i.BudgetUsd,
		&i.CostUsd,
		&i.TokensIn,
		&i.TokensOut,
		&i.State,
		&i.BootDiagnostics,
		&i.StartedAt,
		&i.EndedAt,
		&i.UpdatedAt,
		&i.CredentialID,
		&i.AuthMode,
	)
	return i, err
}

const updateTaskClassification = `-- name: UpdateTaskClassification :one
UPDATE tasks
SET class = $1, updated_at = now()
WHERE id = $2
  AND workspace_id = $3
RETURNING id, workspace_id, source, title, body, class, escalation_level, repo_name, base_branch, branch, state, parent_task_id, created_at, updated_at, next_stage, recovery_stage
`

type UpdateTaskClassificationParams struct {
	Class       string `json:"class"`
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) UpdateTaskClassification(ctx context.Context, arg UpdateTaskClassificationParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskClassification, arg.Class, arg.ID, arg.WorkspaceID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Source,
		&i.Title,
		&i.Body,
		&i.Class,
		&i.EscalationLevel,
		&i.RepoName,
		&i.BaseBranch,
		&i.Branch,
		&i.State,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextStage,
		&i.RecoveryStage,
	)
	return i, err
}

const updateTaskState = `-- name: UpdateTaskState :one
UPDATE tasks
SET state = $1, updated_at = now()
WHERE id = $2
  AND workspace_id = $3
RETURNING id, workspace_id, source, title, body, class, escalation_level, repo_name, base_branch, branch, state, parent_task_id, created_at, updated_at, next_stage, recovery_stage
`

type UpdateTaskStateParams struct {
	State       string `json:"state"`
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskState, arg.State, arg.ID, arg.WorkspaceID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Source,
		&i.Title,
		&i.Body,
		&i.Class,
		&i.EscalationLevel,
		&i.RepoName,
		&i.BaseBranch,
		&i.Branch,
		&i.State,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextStage,
		&i.RecoveryStage,
	)
	return i, err
}

const updateTaskTransition = `-- name: UpdateTaskTransition :one
UPDATE tasks
SET state = $1,
    next_stage = $2,
    recovery_stage = $3,
    updated_at = now()
WHERE id = $4
  AND workspace_id = $5
RETURNING id, workspace_id, source, title, body, class, escalation_level, repo_name, base_branch, branch, state, parent_task_id, created_at, updated_at, next_stage, recovery_stage
`

type UpdateTaskTransitionParams struct {
	State         string `json:"state"`
	NextStage     string `json:"next_stage"`
	RecoveryStage string `json:"recovery_stage"`
	ID            string `json:"id"`
	WorkspaceID   string `json:"workspace_id"`
}

func (q *Queries) UpdateTaskTransition(ctx context.Context, arg UpdateTaskTransitionParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskTransition,
		arg.State,
		arg.NextStage,
		arg.RecoveryStage,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Source,
		&i.Title,
		&i.Body,
		&i.Class,
		&i.EscalationLevel,
		&i.RepoName,
		&i.BaseBranch,
		&i.Branch,
		&i.State,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextStage,
		&i.RecoveryStage,
	)
	return i, err
}

const upsertCredential = `-- name: UpsertCredential :exec
INSERT INTO credentials (
    id, owner_id, owner_kind, kind, vendor, harness, enc_ref
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE
SET owner_id = EXCLUDED.owner_id,
    owner_kind = EXCLUDED.owner_kind,
    kind = EXCLUDED.kind,
    vendor = EXCLUDED.vendor,
    harness = EXCLUDED.harness,
    enc_ref = EXCLUDED.enc_ref,
    updated_at = now()
`

type UpsertCredentialParams struct {
	ID        string `json:"id"`
	OwnerID   string `json:"owner_id"`
	OwnerKind string `json:"owner_kind"`
	Kind      string `json:"kind"`
	Vendor    string `json:"vendor"`
	Harness   string `json:"harness"`
	EncRef    string `json:"enc_ref"`
}

func (q *Queries) UpsertCredential(ctx context.Context, arg UpsertCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertCredential,
		arg.ID,
		arg.OwnerID,
		arg.OwnerKind,
		arg.Kind,
		arg.Vendor,
		arg.Harness,
		arg.EncRef,
	)
	return err
}

const upsertRepo = `-- name: UpsertRepo :exec
INSERT INTO repos (workspace_id, name, url, github_slug, default_base, devcontainer_path)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (workspace_id, name) DO UPDATE
SET url = EXCLUDED.url,
    github_slug = EXCLUDED.github_slug,
    default_base = EXCLUDED.default_base,
    devcontainer_path = EXCLUDED.devcontainer_path
`

type UpsertRepoParams struct {
	WorkspaceID      string `json:"workspace_id"`
	Name             string `json:"name"`
	Url              string `json:"url"`
	GithubSlug       string `json:"github_slug"`
	DefaultBase      string `json:"default_base"`
	DevcontainerPath string `json:"devcontainer_path"`
}

func (q *Queries) UpsertRepo(ctx context.Context, arg UpsertRepoParams) error {
	_, err := q.db.Exec(ctx, upsertRepo,
		arg.WorkspaceID,
		arg.Name,
		arg.Url,
		arg.GithubSlug,
		arg.DefaultBase,
		arg.DevcontainerPath,
	)
	return err
}

const upsertTranscript = `-- name: UpsertTranscript :one
INSERT INTO transcripts (job_id, uri, redaction_stats, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (job_id) DO UPDATE
SET uri = EXCLUDED.uri,
    redaction_stats = EXCLUDED.redaction_stats
RETURNING job_id, uri, redaction_stats, created_at
`

type UpsertTranscriptParams struct {
	JobID          string             `json:"job_id"`
	Uri            string             `json:"uri"`
	RedactionStats []byte             `json:"redaction_stats"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertTranscript(ctx context.Context, arg UpsertTranscriptParams) (Transcript, error) {
	row := q.db.QueryRow(ctx, upsertTranscript,
		arg.JobID,
		arg.Uri,
		arg.RedactionStats,
		arg.CreatedAt,
	)
	var i Transcript
	err := row.Scan(
		&i.JobID,
		&i.Uri,
		&i.RedactionStats,
		&i.CreatedAt,
	)
	return i, err
}

const upsertVendorPolicy = `-- name: UpsertVendorPolicy :exec
INSERT INTO vendor_policies (
    vendor, harness, auth_mode, subscription_headless, reviewed_at, source_url
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (vendor, harness, auth_mode) DO UPDATE
SET subscription_headless = EXCLUDED.subscription_headless,
    reviewed_at = EXCLUDED.reviewed_at,
    source_url = EXCLUDED.source_url,
    updated_at = now()
`

type UpsertVendorPolicyParams struct {
	Vendor               string      `json:"vendor"`
	Harness              string      `json:"harness"`
	AuthMode             string      `json:"auth_mode"`
	SubscriptionHeadless string      `json:"subscription_headless"`
	ReviewedAt           pgtype.Date `json:"reviewed_at"`
	SourceUrl            string      `json:"source_url"`
}

func (q *Queries) UpsertVendorPolicy(ctx context.Context, arg UpsertVendorPolicyParams) error {
	_, err := q.db.Exec(ctx, upsertVendorPolicy,
		arg.Vendor,
		arg.Harness,
		arg.AuthMode,
		arg.SubscriptionHeadless,
		arg.ReviewedAt,
		arg.SourceUrl,
	)
	return err
}

const upsertWorkspace = `-- name: UpsertWorkspace :exec
INSERT INTO workspaces (id, name, config_yaml)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    config_yaml = EXCLUDED.config_yaml
`

type UpsertWorkspaceParams struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	ConfigYaml string `json:"config_yaml"`
}

func (q *Queries) UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) error {
	_, err := q.db.Exec(ctx, upsertWorkspace, arg.ID, arg.Name, arg.ConfigYaml)
	return err
}
