// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: control_plane.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertUserForgeToken = `-- name: UpsertUserForgeToken :one
INSERT INTO user_forge_tokens (user_id, cipher_nonce, ciphertext, forge_login, stored_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (user_id) DO UPDATE SET cipher_nonce=EXCLUDED.cipher_nonce,
ciphertext=EXCLUDED.ciphertext, forge_login=EXCLUDED.forge_login, stored_at=EXCLUDED.stored_at
RETURNING user_id, cipher_nonce, ciphertext, forge_login, stored_at
`

type UpsertUserForgeTokenParams struct {
	UserID      string `json:"user_id"`
	CipherNonce []byte `json:"cipher_nonce"`
	Ciphertext  []byte `json:"ciphertext"`
	ForgeLogin  string `json:"forge_login"`
}

func (q *Queries) UpsertUserForgeToken(ctx context.Context, arg UpsertUserForgeTokenParams) (UserForgeToken, error) {
	row := q.db.QueryRow(ctx, upsertUserForgeToken, arg.UserID, arg.CipherNonce, arg.Ciphertext, arg.ForgeLogin)
	var item UserForgeToken
	err := row.Scan(&item.UserID, &item.CipherNonce, &item.Ciphertext, &item.ForgeLogin, &item.StoredAt)
	return item, err
}

const deleteUserForgeToken = `-- name: DeleteUserForgeToken :execrows
DELETE FROM user_forge_tokens WHERE user_id = $1
`

func (q *Queries) DeleteUserForgeToken(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserForgeToken, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserForgeTokenStatus = `-- name: GetUserForgeTokenStatus :one
SELECT u.status, (f.user_id IS NOT NULL AND u.status='active') AS configured,
CASE WHEN u.status='active' THEN f.forge_login END,
CASE WHEN u.status='active' THEN f.stored_at END
FROM users u LEFT JOIN user_forge_tokens f ON f.user_id=u.id WHERE u.id=$1
`

type GetUserForgeTokenStatusRow struct {
	Status     string             `json:"status"`
	Configured bool               `json:"configured"`
	ForgeLogin pgtype.Text        `json:"forge_login"`
	StoredAt   pgtype.Timestamptz `json:"stored_at"`
}

func (q *Queries) GetUserForgeTokenStatus(ctx context.Context, userID string) (GetUserForgeTokenStatusRow, error) {
	row := q.db.QueryRow(ctx, getUserForgeTokenStatus, userID)
	var item GetUserForgeTokenStatusRow
	err := row.Scan(&item.Status, &item.Configured, &item.ForgeLogin, &item.StoredAt)
	return item, err
}

const getUserForgeTokenForUse = `-- name: GetUserForgeTokenForUse :one
SELECT f.user_id,f.cipher_nonce,f.ciphertext,f.forge_login,f.stored_at
FROM user_forge_tokens f JOIN users u ON u.id=f.user_id AND u.status='active'
WHERE f.user_id=$1
`

func (q *Queries) GetUserForgeTokenForUse(ctx context.Context, userID string) (UserForgeToken, error) {
	row := q.db.QueryRow(ctx, getUserForgeTokenForUse, userID)
	var item UserForgeToken
	err := row.Scan(&item.UserID, &item.CipherNonce, &item.Ciphertext, &item.ForgeLogin, &item.StoredAt)
	return item, err
}

const listUserForgeTokensForRedaction = `-- name: ListUserForgeTokensForRedaction :many
SELECT user_id,cipher_nonce,ciphertext,forge_login,stored_at FROM user_forge_tokens ORDER BY user_id
`

func (q *Queries) ListUserForgeTokensForRedaction(ctx context.Context) ([]UserForgeToken, error) {
	rows, err := q.db.Query(ctx, listUserForgeTokensForRedaction)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserForgeToken{}
	for rows.Next() {
		var item UserForgeToken
		if err := rows.Scan(&item.UserID, &item.CipherNonce, &item.Ciphertext, &item.ForgeLogin, &item.StoredAt); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	return items, rows.Err()
}
