// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Credential struct {
	ID             string             `json:"id"`
	OwnerID        string             `json:"owner_id"`
	OwnerKind      string             `json:"owner_kind"`
	Kind           string             `json:"kind"`
	Harness        string             `json:"harness"`
	EncRef         string             `json:"enc_ref"`
	RateLimitState string             `json:"rate_limit_state"`
	PolicyFlag     string             `json:"policy_flag"`
	CooldownUntil  pgtype.Timestamptz `json:"cooldown_until"`
	LastError      string             `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Vendor         string             `json:"vendor"`
	LeasedBy       string             `json:"leased_by"`
	LeaseUntil     pgtype.Timestamptz `json:"lease_until"`
	LeaseTaskID    string             `json:"lease_task_id"`
}

type Event struct {
	ID          int64              `json:"id"`
	TaskID      string             `json:"task_id"`
	JobID       pgtype.Text        `json:"job_id"`
	Kind        string             `json:"kind"`
	ActorID     string             `json:"actor_id"`
	ActorRole   string             `json:"actor_role"`
	PayloadJson []byte             `json:"payload_json"`
	At          pgtype.Timestamptz `json:"at"`
}

type Intervention struct {
	ID         int64              `json:"id"`
	TaskID     string             `json:"task_id"`
	JobID      pgtype.Text        `json:"job_id"`
	ActorID    string             `json:"actor_id"`
	ActorRole  string             `json:"actor_role"`
	Action     string             `json:"action"`
	ReasonCode string             `json:"reason_code"`
	Comment    string             `json:"comment"`
	At         pgtype.Timestamptz `json:"at"`
}

type Job struct {
	ID              string             `json:"id"`
	TaskID          string             `json:"task_id"`
	Stage           string             `json:"stage"`
	Harness         string             `json:"harness"`
	ModelTier       string             `json:"model_tier"`
	Runner          string             `json:"runner"`
	SandboxRef      string             `json:"sandbox_ref"`
	PackVersion     string             `json:"pack_version"`
	ConfinementTier string             `json:"confinement_tier"`
	BudgetUsd       float64            `json:"budget_usd"`
	CostUsd         float64            `json:"cost_usd"`
	TokensIn        int64              `json:"tokens_in"`
	TokensOut       int64              `json:"tokens_out"`
	State           string             `json:"state"`
	BootDiagnostics []byte             `json:"boot_diagnostics"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CredentialID    string             `json:"credential_id"`
	AuthMode        string             `json:"auth_mode"`
}

type Repo struct {
	WorkspaceID      string             `json:"workspace_id"`
	Name             string             `json:"name"`
	Url              string             `json:"url"`
	GithubSlug       string             `json:"github_slug"`
	DefaultBase      string             `json:"default_base"`
	DevcontainerPath string             `json:"devcontainer_path"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Task struct {
	ID              string             `json:"id"`
	WorkspaceID     string             `json:"workspace_id"`
	Source          string             `json:"source"`
	Title           string             `json:"title"`
	Body            string             `json:"body"`
	Class           string             `json:"class"`
	EscalationLevel string             `json:"escalation_level"`
	RepoName        string             `json:"repo_name"`
	BaseBranch      string             `json:"base_branch"`
	Branch          string             `json:"branch"`
	State           string             `json:"state"`
	ParentTaskID    string             `json:"parent_task_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Transcript struct {
	JobID          string             `json:"job_id"`
	Uri            string             `json:"uri"`
	RedactionStats []byte             `json:"redaction_stats"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                  string             `json:"id"`
	IdentityProviderRef string             `json:"identity_provider_ref"`
	Role                string             `json:"role"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type VendorPolicy struct {
	Vendor               string             `json:"vendor"`
	Harness              string             `json:"harness"`
	AuthMode             string             `json:"auth_mode"`
	SubscriptionHeadless string             `json:"subscription_headless"`
	ReviewedAt           pgtype.Date        `json:"reviewed_at"`
	SourceUrl            string             `json:"source_url"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	ConfigYaml string             `json:"config_yaml"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type WorkspaceCredential struct {
	WorkspaceID  string `json:"workspace_id"`
	CredentialID string `json:"credential_id"`
}

type WorkspaceVendorPolicy struct {
	WorkspaceID string `json:"workspace_id"`
	Vendor      string `json:"vendor"`
	Harness     string `json:"harness"`
	AuthMode    string `json:"auth_mode"`
}
