// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Artifact struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	Name        string             `json:"name"`
	ContentType string             `json:"content_type"`
	SizeBytes   int64              `json:"size_bytes"`
	Content     []byte             `json:"content"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ArtifactLink struct {
	WorkspaceID string      `json:"workspace_id"`
	ArtifactID  string      `json:"artifact_id"`
	TaskID      pgtype.Text `json:"task_id"`
	FeatureID   pgtype.Text `json:"feature_id"`
}

type Event struct {
	ID          int64              `json:"id"`
	TaskID      pgtype.Text        `json:"task_id"`
	JobID       pgtype.Text        `json:"job_id"`
	Kind        string             `json:"kind"`
	ActorID     string             `json:"actor_id"`
	ActorRole   string             `json:"actor_role"`
	PayloadJson []byte             `json:"payload_json"`
	At          pgtype.Timestamptz `json:"at"`
	WorkspaceID string             `json:"workspace_id"`
}

type Feature struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	ParentID    pgtype.Text        `json:"parent_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type GithubLifecycle struct {
	WorkspaceID       string             `json:"workspace_id"`
	TaskID            string             `json:"task_id"`
	Repository        string             `json:"repository"`
	SpecVersion       int32              `json:"spec_version"`
	Source            string             `json:"source"`
	SourceIssueNumber int32              `json:"source_issue_number"`
	IssueNumber       int32              `json:"issue_number"`
	IssueUrl          string             `json:"issue_url"`
	Outcome           string             `json:"outcome"`
	State             string             `json:"state"`
	Attempts          int32              `json:"attempts"`
	LastError         string             `json:"last_error"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreateState       string             `json:"create_state"`
	CreateAttempts    int32              `json:"create_attempts"`
	ReconcileMisses   int32              `json:"reconcile_misses"`
}

type Intervention struct {
	ID         int64              `json:"id"`
	TaskID     string             `json:"task_id"`
	JobID      pgtype.Text        `json:"job_id"`
	ActorID    string             `json:"actor_id"`
	ActorRole  string             `json:"actor_role"`
	Action     string             `json:"action"`
	ReasonCode string             `json:"reason_code"`
	Comment    string             `json:"comment"`
	At         pgtype.Timestamptz `json:"at"`
}

type Job struct {
	ID              string             `json:"id"`
	TaskID          string             `json:"task_id"`
	Stage           string             `json:"stage"`
	Harness         string             `json:"harness"`
	ModelTier       string             `json:"model_tier"`
	Runner          string             `json:"runner"`
	PackVersion     string             `json:"pack_version"`
	ConfinementTier string             `json:"confinement_tier"`
	CostUsd         float64            `json:"cost_usd"`
	TokensIn        int64              `json:"tokens_in"`
	TokensOut       int64              `json:"tokens_out"`
	State           string             `json:"state"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	AuthMode        string             `json:"auth_mode"`
}

type Repo struct {
	WorkspaceID      string             `json:"workspace_id"`
	Name             string             `json:"name"`
	Url              string             `json:"url"`
	GithubSlug       string             `json:"github_slug"`
	DefaultBase      string             `json:"default_base"`
	DevcontainerPath string             `json:"devcontainer_path"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type ReviewPublication struct {
	ReviewWorkOrderID      string             `json:"review_work_order_id"`
	WorkspaceID            string             `json:"workspace_id"`
	TaskID                 string             `json:"task_id"`
	JobID                  string             `json:"job_id"`
	Verdict                string             `json:"verdict"`
	ReasonCode             string             `json:"reason_code"`
	Summary                string             `json:"summary"`
	Feedback               string             `json:"feedback"`
	ReviewedCommitSha      string             `json:"reviewed_commit_sha"`
	ReviewerModel          string             `json:"reviewer_model"`
	ReviewerSession        string             `json:"reviewer_session"`
	SameModelAsImplementer string             `json:"same_model_as_implementer"`
	State                  string             `json:"state"`
	Attempts               int32              `json:"attempts"`
	CheckRunID             int64              `json:"check_run_id"`
	CommentID              int64              `json:"comment_id"`
	LastError              string             `json:"last_error"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	ReviewRound            int32              `json:"review_round"`
	ReviewSeat             int32              `json:"review_seat"`
	RequiredModel          string             `json:"required_model"`
	RequiredHarness        string             `json:"required_harness"`
	ModelEnforcement       string             `json:"model_enforcement"`
	RequiredEffort         string             `json:"required_effort"`
}

type ReviewRoundRetry struct {
	WorkspaceID string             `json:"workspace_id"`
	RequestID   string             `json:"request_id"`
	TaskID      string             `json:"task_id"`
	Reason      string             `json:"reason"`
	PriorRound  int32              `json:"prior_round"`
	NewRound    int32              `json:"new_round"`
	PrHead      string             `json:"pr_head"`
	ActorID     string             `json:"actor_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Task struct {
	ID              string             `json:"id"`
	WorkspaceID     string             `json:"workspace_id"`
	Source          string             `json:"source"`
	Title           string             `json:"title"`
	Body            string             `json:"body"`
	Class           string             `json:"class"`
	EscalationLevel string             `json:"escalation_level"`
	RepoName        string             `json:"repo_name"`
	BaseBranch      string             `json:"base_branch"`
	Branch          string             `json:"branch"`
	State           string             `json:"state"`
	ParentTaskID    string             `json:"parent_task_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	NextStage       string             `json:"next_stage"`
	RecoveryStage   string             `json:"recovery_stage"`
	FeatureID       pgtype.Text        `json:"feature_id"`
	IntakeKey       pgtype.Text        `json:"intake_key"`
	Mode            string             `json:"mode"`
	SpecApproval    bool               `json:"spec_approval"`
	MergeApproval   bool               `json:"merge_approval"`
	PolicyVersion   int32              `json:"policy_version"`
}

type TaskSpec struct {
	TaskID          string             `json:"task_id"`
	Version         int32              `json:"version"`
	Content         string             `json:"content"`
	AcceptanceCount int32              `json:"acceptance_count"`
	Acceptance      []byte             `json:"acceptance"`
	Decomposition   []byte             `json:"decomposition"`
	Approved        bool               `json:"approved"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
}

type Transcript struct {
	JobID          string             `json:"job_id"`
	Uri            string             `json:"uri"`
	RedactionStats []byte             `json:"redaction_stats"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                  string             `json:"id"`
	IdentityProviderRef string             `json:"identity_provider_ref"`
	Role                string             `json:"role"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type WorkOrder struct {
	ID                    string             `json:"id"`
	WorkspaceID           string             `json:"workspace_id"`
	TaskID                string             `json:"task_id"`
	JobID                 string             `json:"job_id"`
	Stage                 string             `json:"stage"`
	State                 string             `json:"state"`
	ClaimantID            string             `json:"claimant_id"`
	SessionID             string             `json:"session_id"`
	ClientTokenHash       string             `json:"client_token_hash"`
	Agent                 string             `json:"agent"`
	Model                 string             `json:"model"`
	LeaseExpiresAt        pgtype.Timestamptz `json:"lease_expires_at"`
	Progress              string             `json:"progress"`
	CostUsd               float64            `json:"cost_usd"`
	TokensIn              int64              `json:"tokens_in"`
	TokensOut             int64              `json:"tokens_out"`
	SelfReported          bool               `json:"self_reported"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	QueueEnteredAt        pgtype.Timestamptz `json:"queue_entered_at"`
	QueueDeadline         pgtype.Timestamptz `json:"queue_deadline"`
	ExecutionStartedAt    pgtype.Timestamptz `json:"execution_started_at"`
	ExecutionDeadline     pgtype.Timestamptz `json:"execution_deadline"`
	RedispatchCount       int32              `json:"redispatch_count"`
	WorkerID              string             `json:"worker_id"`
	ReviewRound           int32              `json:"review_round"`
	ReviewSeat            int32              `json:"review_seat"`
	RequiredModel         string             `json:"required_model"`
	RequiredHarness       string             `json:"required_harness"`
	ModelEnforcement      string             `json:"model_enforcement"`
	RequiredHarnessConfig []byte             `json:"required_harness_config"`
	ExecutionTimeout      string             `json:"execution_timeout"`
	LastAttemptOutcome    string             `json:"last_attempt_outcome"`
	LastFailureMessage    string             `json:"last_failure_message"`
	LastFailureExitStatus pgtype.Int4        `json:"last_failure_exit_status"`
	LastFailureAt         pgtype.Timestamptz `json:"last_failure_at"`
	AutomaticRetryCount   int32              `json:"automatic_retry_count"`
	NextRetryAt           pgtype.Timestamptz `json:"next_retry_at"`
	RetrySuppressed       bool               `json:"retry_suppressed"`
}

type WorkOrderRecovery struct {
	WorkspaceID string             `json:"workspace_id"`
	WorkOrderID string             `json:"work_order_id"`
	RequestID   string             `json:"request_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Worker struct {
	ID             string             `json:"id"`
	WorkspaceID    string             `json:"workspace_id"`
	Name           string             `json:"name"`
	CredentialHash string             `json:"credential_hash"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	ProbeResults   []byte             `json:"probe_results"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type WorkerPairing struct {
	TokenHash   string             `json:"token_hash"`
	WorkspaceID string             `json:"workspace_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Workspace struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	ConfigYaml    string             `json:"config_yaml"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ConfigVersion int64              `json:"config_version"`
}
