// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	ApproveLatestSpecVersion(ctx context.Context, arg ApproveLatestSpecVersionParams) (TaskSpec, error)
	BindTaskApproval(ctx context.Context, arg BindTaskApprovalParams) (Task, error)
	CountEvents(ctx context.Context, arg CountEventsParams) (int64, error)
	// The §21.17 check-in window: events of a kind recorded after the latest
	// human intervention on the task (all of them when no human has intervened).
	CountEventsSinceHumanIntervention(ctx context.Context, arg CountEventsSinceHumanInterventionParams) (int64, error)
	GetJob(ctx context.Context, arg GetJobParams) (Job, error)
	GetLatestJob(ctx context.Context, arg GetLatestJobParams) (Job, error)
	GetLatestSpecVersion(ctx context.Context, arg GetLatestSpecVersionParams) (TaskSpec, error)
	GetTask(ctx context.Context, arg GetTaskParams) (Task, error)
	GetTaskByIntakeKey(ctx context.Context, arg GetTaskByIntakeKeyParams) (Task, error)
	GetTranscript(ctx context.Context, arg GetTranscriptParams) (Transcript, error)
	GetWorkspaceConfig(ctx context.Context, id string) (Workspace, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error)
	InsertIntervention(ctx context.Context, arg InsertInterventionParams) (Intervention, error)
	InsertJob(ctx context.Context, arg InsertJobParams) (Job, error)
	InsertSpecVersion(ctx context.Context, arg InsertSpecVersionParams) (TaskSpec, error)
	InsertTask(ctx context.Context, arg InsertTaskParams) (Task, error)
	InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) (Workspace, error)
	InsertWorkspaceEvent(ctx context.Context, arg InsertWorkspaceEventParams) (Event, error)
	ListActivityMarkers(ctx context.Context, workspaceID string) ([]ListActivityMarkersRow, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]Event, error)
	ListInterventions(ctx context.Context, arg ListInterventionsParams) ([]Intervention, error)
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error)
	ListTasks(ctx context.Context, workspaceID string) ([]Task, error)
	MarkTaskApprovalStale(ctx context.Context, arg MarkTaskApprovalStaleParams) (Task, error)
	SkipTaskRefresh(ctx context.Context, arg SkipTaskRefreshParams) (Task, error)
	UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error)
	UpdateTaskClassification(ctx context.Context, arg UpdateTaskClassificationParams) (Task, error)
	UpdateTaskHold(ctx context.Context, arg UpdateTaskHoldParams) (Task, error)
	UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) (Task, error)
	UpdateTaskTransition(ctx context.Context, arg UpdateTaskTransitionParams) (Task, error)
	UpdateWorkspaceConfig(ctx context.Context, arg UpdateWorkspaceConfigParams) (Workspace, error)
	UpsertRepo(ctx context.Context, arg UpsertRepoParams) error
	UpsertTranscript(ctx context.Context, arg UpsertTranscriptParams) (Transcript, error)
}

var _ Querier = (*Queries)(nil)
