// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	DeactivateIdentityUser(ctx context.Context, id string) (User, error)
	GetIdentityUser(ctx context.Context, id string) (User, error)
	GetUserForgeTokenForUse(ctx context.Context, userID string) (UserForgeToken, error)
	GetUserForgeTokenStatus(ctx context.Context, userID string) (GetUserForgeTokenStatusRow, error)
	GetUserTokenByHash(ctx context.Context, tokenHash []byte) (GetUserTokenByHashRow, error)
	InsertDeploymentCredential(ctx context.Context, arg InsertDeploymentCredentialParams) (UserToken, error)
	InsertIdentityUser(ctx context.Context, arg InsertIdentityUserParams) (User, error)
	InsertUserToken(ctx context.Context, arg InsertUserTokenParams) (UserToken, error)
	ListOwnUserTokens(ctx context.Context, userID string) ([]ListOwnUserTokensRow, error)
	ListUserForgeTokensForRedaction(ctx context.Context) ([]UserForgeToken, error)
	MarkUserTokenUsed(ctx context.Context, arg MarkUserTokenUsedParams) (int64, error)
	RevokeOwnUserToken(ctx context.Context, arg RevokeOwnUserTokenParams) (UserToken, error)
	RevokeUserToken(ctx context.Context, id string) (UserToken, error)
	UpsertUserForgeToken(ctx context.Context, arg UpsertUserForgeTokenParams) (UserForgeToken, error)
	DeleteUserForgeToken(ctx context.Context, userID string) (int64, error)
	UpdateDeploymentOrgName(ctx context.Context, name string) (Org, error)
	ApproveLatestSpecVersion(ctx context.Context, arg ApproveLatestSpecVersionParams) (TaskSpec, error)
	BindTaskApproval(ctx context.Context, arg BindTaskApprovalParams) (Task, error)
	CountEvents(ctx context.Context, arg CountEventsParams) (int64, error)
	// The check-in window: events of a kind recorded after the latest
	// human intervention on the task (all of them when no human has intervened).
	CountEventsSinceHumanIntervention(ctx context.Context, arg CountEventsSinceHumanInterventionParams) (int64, error)
	CountTaskOperationsTasks(ctx context.Context, arg CountTaskOperationsTasksParams) (int64, error)
	DeleteLineageLink(ctx context.Context, arg DeleteLineageLinkParams) error
	GetJob(ctx context.Context, arg GetJobParams) (Job, error)
	GetLatestJob(ctx context.Context, arg GetLatestJobParams) (Job, error)
	GetLatestSpecVersion(ctx context.Context, arg GetLatestSpecVersionParams) (TaskSpec, error)
	GetTask(ctx context.Context, arg GetTaskParams) (Task, error)
	GetTaskByIntakeKey(ctx context.Context, arg GetTaskByIntakeKeyParams) (Task, error)
	GetTranscript(ctx context.Context, arg GetTranscriptParams) (Transcript, error)
	GetWorkspaceConfig(ctx context.Context, id string) (Workspace, error)
	InsertDeploymentEvent(ctx context.Context, arg InsertDeploymentEventParams) error
	InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error)
	InsertIntervention(ctx context.Context, arg InsertInterventionParams) (Intervention, error)
	InsertJob(ctx context.Context, arg InsertJobParams) (Job, error)
	InsertLineageLink(ctx context.Context, arg InsertLineageLinkParams) error
	InsertSpecVersion(ctx context.Context, arg InsertSpecVersionParams) (TaskSpec, error)
	InsertTask(ctx context.Context, arg InsertTaskParams) (Task, error)
	InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) (Workspace, error)
	InsertWorkspaceEvent(ctx context.Context, arg InsertWorkspaceEventParams) (Event, error)
	ListActivityMarkers(ctx context.Context, workspaceID string) ([]ListActivityMarkersRow, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]Event, error)
	ListRequirementEvents(ctx context.Context, arg ListRequirementEventsParams) ([]Event, error)
	ListTaskOperationsEvents(ctx context.Context, arg ListTaskOperationsEventsParams) ([]Event, error)
	ListTaskOperationsLatestPlans(ctx context.Context, arg ListTaskOperationsLatestPlansParams) ([]TaskSpec, error)
	ListTaskOperationsTasks(ctx context.Context, arg ListTaskOperationsTasksParams) ([]ListTaskOperationsTasksRow, error)
	ListInterventions(ctx context.Context, arg ListInterventionsParams) ([]Intervention, error)
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error)
	ListCheckpointContextCandidates(ctx context.Context, arg ListCheckpointContextCandidatesParams) ([]ListCheckpointContextCandidatesRow, error)
	ListLineageLinks(ctx context.Context, workspaceID string) ([]Link, error)
	ListWorkspaceEvents(ctx context.Context, workspaceID string) ([]Event, error)
	ListTasks(ctx context.Context, workspaceID string) ([]ListTasksRow, error)
	MarkTaskApprovalStale(ctx context.Context, arg MarkTaskApprovalStaleParams) (Task, error)
	SkipTaskRefresh(ctx context.Context, arg SkipTaskRefreshParams) (Task, error)
	UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error)
	UpdateTaskClassification(ctx context.Context, arg UpdateTaskClassificationParams) (Task, error)
	UpdateTaskHold(ctx context.Context, arg UpdateTaskHoldParams) (Task, error)
	UpdateTaskAssignee(ctx context.Context, arg UpdateTaskAssigneeParams) (Task, error)
	UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) (Task, error)
	UpdateTaskTransition(ctx context.Context, arg UpdateTaskTransitionParams) (Task, error)
	UpdateWorkspaceConfig(ctx context.Context, arg UpdateWorkspaceConfigParams) (Workspace, error)
	UpsertRepo(ctx context.Context, arg UpsertRepoParams) error
	UpsertTranscript(ctx context.Context, arg UpsertTranscriptParams) (Transcript, error)
	DeleteLineageLinks(ctx context.Context, workspaceID string) (int64, error)
}

var _ Querier = (*Queries)(nil)
