// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	ClaimCredential(ctx context.Context, arg ClaimCredentialParams) (Credential, error)
	DeleteWorkspaceCredentialRefs(ctx context.Context, workspaceID string) error
	DeleteWorkspaceVendorPolicyRefs(ctx context.Context, workspaceID string) error
	DisableCredentialIfUnreferenced(ctx context.Context, id string) error
	EnableCredential(ctx context.Context, id string) error
	GetJob(ctx context.Context, arg GetJobParams) (Job, error)
	GetLatestJob(ctx context.Context, arg GetLatestJobParams) (Job, error)
	GetTask(ctx context.Context, arg GetTaskParams) (Task, error)
	GetTranscript(ctx context.Context, arg GetTranscriptParams) (Transcript, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error)
	InsertIntervention(ctx context.Context, arg InsertInterventionParams) (Intervention, error)
	InsertJob(ctx context.Context, arg InsertJobParams) (Job, error)
	InsertTask(ctx context.Context, arg InsertTaskParams) (Task, error)
	InsertWorkspaceCredentialRef(ctx context.Context, arg InsertWorkspaceCredentialRefParams) error
	InsertWorkspaceVendorPolicyRef(ctx context.Context, arg InsertWorkspaceVendorPolicyRefParams) error
	ListActivityMarkers(ctx context.Context, workspaceID string) ([]ListActivityMarkersRow, error)
	ListCredentials(ctx context.Context) ([]Credential, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]Event, error)
	ListInterventions(ctx context.Context, arg ListInterventionsParams) ([]Intervention, error)
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error)
	ListTasks(ctx context.Context, workspaceID string) ([]Task, error)
	ListVendorPolicies(ctx context.Context) ([]VendorPolicy, error)
	ListWorkspaceCredentialIDs(ctx context.Context, workspaceID string) ([]string, error)
	ListWorkspaceVendorPolicyRefs(ctx context.Context, workspaceID string) ([]ListWorkspaceVendorPolicyRefsRow, error)
	ReleaseCredential(ctx context.Context, arg ReleaseCredentialParams) (int64, error)
	RescueTaskCredentialLeases(ctx context.Context, arg RescueTaskCredentialLeasesParams) (int64, error)
	RestrictVendorPolicyIfUnreferenced(ctx context.Context, arg RestrictVendorPolicyIfUnreferencedParams) error
	ThrottleCredential(ctx context.Context, arg ThrottleCredentialParams) (int64, error)
	UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error)
	UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) (Task, error)
	UpsertCredential(ctx context.Context, arg UpsertCredentialParams) error
	UpsertRepo(ctx context.Context, arg UpsertRepoParams) error
	UpsertTranscript(ctx context.Context, arg UpsertTranscriptParams) (Transcript, error)
	UpsertVendorPolicy(ctx context.Context, arg UpsertVendorPolicyParams) error
	UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) error
}

var _ Querier = (*Queries)(nil)
