// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: control_plane.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertWorkspaceForgeToken = `-- name: UpsertWorkspaceForgeToken :one
INSERT INTO workspace_forge_tokens (workspace_id, cipher_nonce, ciphertext, forge_login, stored_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (workspace_id) DO UPDATE SET cipher_nonce=EXCLUDED.cipher_nonce,
ciphertext=EXCLUDED.ciphertext, forge_login=EXCLUDED.forge_login, stored_at=EXCLUDED.stored_at
RETURNING workspace_id, cipher_nonce, ciphertext, forge_login, stored_at
`

type UpsertWorkspaceForgeTokenParams struct {
	WorkspaceID string `json:"workspace_id"`
	CipherNonce []byte `json:"cipher_nonce"`
	Ciphertext  []byte `json:"ciphertext"`
	ForgeLogin  string `json:"forge_login"`
}

func (q *Queries) UpsertWorkspaceForgeToken(ctx context.Context, arg UpsertWorkspaceForgeTokenParams) (WorkspaceForgeToken, error) {
	row := q.db.QueryRow(ctx, upsertWorkspaceForgeToken, arg.WorkspaceID, arg.CipherNonce, arg.Ciphertext, arg.ForgeLogin)
	var item WorkspaceForgeToken
	err := row.Scan(&item.WorkspaceID, &item.CipherNonce, &item.Ciphertext, &item.ForgeLogin, &item.StoredAt)
	return item, err
}

const deleteWorkspaceForgeToken = `-- name: DeleteWorkspaceForgeToken :execrows
DELETE FROM workspace_forge_tokens WHERE workspace_id = $1
`

func (q *Queries) DeleteWorkspaceForgeToken(ctx context.Context, workspaceID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkspaceForgeToken, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkspaceForgeTokenStatus = `-- name: GetWorkspaceForgeTokenStatus :one
SELECT w.id AS workspace_id, (f.workspace_id IS NOT NULL) AS configured,
f.forge_login, f.stored_at
FROM workspaces w LEFT JOIN workspace_forge_tokens f ON f.workspace_id=w.id
WHERE w.id=$1
`

type GetWorkspaceForgeTokenStatusRow struct {
	WorkspaceID string             `json:"workspace_id"`
	Configured  bool               `json:"configured"`
	ForgeLogin  pgtype.Text        `json:"forge_login"`
	StoredAt    pgtype.Timestamptz `json:"stored_at"`
}

func (q *Queries) GetWorkspaceForgeTokenStatus(ctx context.Context, workspaceID string) (GetWorkspaceForgeTokenStatusRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceForgeTokenStatus, workspaceID)
	var item GetWorkspaceForgeTokenStatusRow
	err := row.Scan(&item.WorkspaceID, &item.Configured, &item.ForgeLogin, &item.StoredAt)
	return item, err
}

const getWorkspaceForgeTokenForUse = `-- name: GetWorkspaceForgeTokenForUse :one
SELECT workspace_id,cipher_nonce,ciphertext,forge_login,stored_at
FROM workspace_forge_tokens WHERE workspace_id=$1
`

func (q *Queries) GetWorkspaceForgeTokenForUse(ctx context.Context, workspaceID string) (WorkspaceForgeToken, error) {
	row := q.db.QueryRow(ctx, getWorkspaceForgeTokenForUse, workspaceID)
	var item WorkspaceForgeToken
	err := row.Scan(&item.WorkspaceID, &item.CipherNonce, &item.Ciphertext, &item.ForgeLogin, &item.StoredAt)
	return item, err
}

const listWorkspaceForgeTokensForRedaction = `-- name: ListWorkspaceForgeTokensForRedaction :many
SELECT workspace_id,cipher_nonce,ciphertext,forge_login,stored_at
FROM workspace_forge_tokens ORDER BY workspace_id
`

func (q *Queries) ListWorkspaceForgeTokensForRedaction(ctx context.Context) ([]WorkspaceForgeToken, error) {
	rows, err := q.db.Query(ctx, listWorkspaceForgeTokensForRedaction)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceForgeToken{}
	for rows.Next() {
		var item WorkspaceForgeToken
		if err := rows.Scan(&item.WorkspaceID, &item.CipherNonce, &item.Ciphertext, &item.ForgeLogin, &item.StoredAt); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	return items, rows.Err()
}
